### ISSUE TITLE
[BUG][Swift][SPM] StatusCode == 200, but it is Error..!

### ISSUE THREAD

**Issue by sangkuOH** [OpenAPITools/openapi-generator#10357]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
response comes from API
The statusCode == 200, but it comes to case .failure
The message  == The data couldn’t be read because it isn’t in the correct format.
data also comes.

in proccessing of builder, something wrong I guess.

##### openapi-generator version
latest version.

##### OpenAPI declaration file content or url

https://github.com/iCloudHospital/ch-api-client-swift/releases/tag/1.7.4

##### Generation Details
- This issue comes when I convert to cocoaPod to SPM env.

**Comment by 4brunu** [comment]
Hey, 
Can you please check if the data format you received is the data that tou are expecting?
I had similar issues, but it was the servers that was sending a response that was not agreed in the swagger file.
Can you be more specific with the error and create a sample project where I could reproduce this issue?
It's weird that this happened when migrating from cocoapods to SPM, because it should have any influence on this.
