### ISSUE TITLE
[REQ] Improve 'spring-boot' generator to remove dependency to allow disable springfox support

### ISSUE THREAD

**Issue by ghilainm** [OpenAPITools/openapi-generator#10409]
### Is your feature request related to a problem? Please describe.

Yes, i don't want to use springfox and it is automatically added to the generated classes.

## Describe the solution you'd like

New option to disable springfox support if not wanted.

## Describe alternatives you've considered

Post processing resources generated, or override default template, but seems like a burden which shouldn't be imposed to all spring-boot generator clients.

**Comment by bennypi** [comment]
I would really like to see this improvement implemented, not only because one may not like springfox, but because right now springfox and spring boot 2.6 do not work together. Apparently springfox is also no longer maintained, there hasn't been a commit to the repository in over a year.

Please see these two issues at the spring fox repository for in incompatibility with spring boot 2.6:
https://github.com/springfox/springfox/issues/3462
https://github.com/springfox/springfox/issues/3934

As far as I can tell, the spring boot generator does not work with spring boot 2.6.

**Comment by wing328** [comment]
Closed via #11181. Please pull the latest master to give it another try.
