### ISSUE TITLE
[typescript-axios] app cannot build due to error with common.ts (unexpected token)

### ISSUE THREAD

**Issue by olrtg** [OpenAPITools/openapi-generator#10781]
##### Description
Hi guys! this is the first time that i'm using openapi-generator. The problem that i encountered is that my ionic/vue/ts app doesn't build due to an error in the common.ts file.

##### openapi-generator version
5.3.0

##### OpenAPI declaration file content or url
https://citapp.goyburu.com/api/v1/openapi.json

##### Command line used for generation
```bash
./node_modules/@openapitools/openapi-generator-cli/main.js generate -i https://citapp.goyburu.com/api/v1/openapi.json -g typescript-axios -o ./api/generated
```

##### Related issues/PRs
I didn't found any related issues. But i found a thread in stackoverflow:
https://stackoverflow.com/questions/66360419/failed-to-compile-using-openapi-ts-module-with-react-you-may-need-an-addition

##### Suggest a fix/enhancement
This is the line that is creating the build error is this one:
https://github.com/OpenAPITools/openapi-generator/blob/c2c4ba5b06c2107ad466c20dfee7a8f191a25139/modules/openapi-generator/src/main/resources/typescript-axios/common.mustache#L124

A screenshot of the error:
![Screenshot](https://i.ibb.co/QD9X2Zz/Screen-Shot-2021-11-04-at-14-56-08.png)

**Comment by code1x1** [comment]
the problem seems to be that your typescript webpack project doesnt support optional chaining
https://github.com/webpack/webpack/issues/10227
https://stackoverflow.com/questions/58813176/webpack-cant-compile-ts-3-7-optional-chaining-nullish-coalescing

This stackoverflow response suggests to use the right babel-loader plugins or using es2018 in your tsconfig.json
https://stackoverflow.com/a/61258647

**Comment by olrtg** [comment]
Hey! Thanks for response.. that actually did the trick for me.
Sorry for the late reply
