### ISSUE TITLE
[BUG] [swift5] Update the Swift 5 bearer token authentication examples

### ISSUE THREAD

**Issue by denizdogan** [OpenAPITools/openapi-generator#11002]
The following examples are outdated with respect to the current Swift 5 implementation. The primary issue here is that the execute method nowadays returns `URLSessionTask?` whereas the examples are working with `Void` as the return type.

I've tried to update the examples to get a working implementation myself, alas, I don't quite understand how to do it.

- Wiki: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-do-i-implement-bearer-token-authentication-with-urlsession-on-the-swift-api-client
- Example source code: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/swift5/urlsessionLibrary/SwaggerClientTests/SwaggerClient/BearerDecodableRequestBuilder.swift

@4brunu

**Comment by 4brunu** [comment]
You are right, this is big a problem, introducing request cancelation, broke the authentication flow with URLSession.
Basically at this moment, we can have task cancelation or the authentication flow, but not the two at the same time.
This is not a trivial problem.
By introducing a semaphore, we could wait for the token refresh, assign the URLSessionTask to a variable and then return it, but this would introduce the necessity of calling all the methods in a a background thread.
Or we can try to do something similar to the URLSessionImplementations.taskCompletionShouldRetry but even that has the same issue.
I would like to ask @DavidHorvath and @funzin if you guys have any suggestion to fix this, because this is a major issue, that can lead to many changes.

**Comment by 4brunu** [comment]
A quick workaround would be to disable task cancelation and return nil, but we need to find a solution for this, to use both request cancelation and authentication flow at the same time.

**Comment by 4brunu** [comment]
By the way, with alamofire, everything is working. Maybe we need to create a wrapper around URLSession to allow the configuration of the request before its executed, and also a retry after is executed, basically to create an adapter and retrier like alamofire has?

**Comment by 4brunu** [comment]
I think I found a solution inspired in RxSwift/Combine, instead of returning URLSessionTask we would return a OpenAPIRequestCancelable, similar to Combine AnyCancellable, that have a private property URLSessionTask that is updated accordingly to the current request. What do you think? I will try to create a draft to see if this works.
By the way, @jarrodparkes if you want to help with this, you are welcome 🙂

**Comment by denizdogan** [comment]
@4brunu I appreciate your efforts with this! However, I'm still too new to all of this to really be the judge of what makes a good solution. :)
