### ISSUE TITLE
[BUG] [Python] Model initialization does not accept iterable postitional arguments

### ISSUE THREAD

**Issue by ckoegel** [OpenAPITools/openapi-generator#11092]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating models from openapi schemas, these objects do not accept iterable objects for initializing new instances. The `init` function accepts both `*args` and `**kwargs`, but the file `invalid_pos_args.mustache` causes an `ApiTypeError` if any `*args` are passed in. 

##### openapi-generator version

0.5.3

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model_templates/invalid_pos_args.mustache
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model_templates/model_normal.mustache

##### Generation Details

using the spec at https://github.com/Bandwidth/api-docs/blob/main/site/specs-source/messaging.json and generating using `openapi-generator-cli generate -g python -i messaging.json -o ./msg-test` allows for viewing the generated SDK,

##### Steps to reproduce

After generating, attempting to create a BandwidthCallbackMessage by passing in a dict, ex: `BandwidthCallbackMessage(my_dict)` causes the ApiTypeError "Invalid positional arguments...". This can be avoided by using `**kwargs`, ex: `BandwidthCallbackMessage(**my_dict)`, but since the message attribute is also an object (BandwidthMessage), the same issue arises, nested in the creation of BandwidthCallbackMessage, and the error is thrown anyway.

##### Related issues/PRs

None

##### Suggest a fix

By creating the instance of BandwidthCallbackMessage using BandwidthCallbackMessage(**my_dict), and then putting the code below inside the `for var_name, var_vlaue in kwargs.items():` loop inside the __init__ function of the generated model file, I was able to generate both objects successfully.
```
if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            if var_name == "message":
                setattr(self, var_name, BandwidthMessage(**var_value))
            else:
                setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
```
This solution is honestly horrendous and only works for this very specific use case, but shows that it can be done. I will be attempting to modify the logic inside the `if args:` statement in the same file to recursively check for objects in the args field and convert them to kwargs to be set normally. This solution should allow for a much more standardized solution to the issue. I'll be making a PR with my progress on this.

**Comment by spacether** [comment]
@ckoegel this suggestion is concerning for a couple of reasons.
The example that you include appears to be for a type object model which in python is a dictionary.
In the type signatures required parameters are listed first, then optional parameters.
The fundamental source of that information is the map of property names to property schemas in a yaml or json spec.
The parsing and loading of those specs and schemas is done in Java prior to the code being generated in python.
For your feature request to work, the order of the keys must always be the same whether the spec is written in json or yaml.

## Spec requirements from yaml + json

### Yaml
- https://yaml.org/spec/1.2.2/#3221-mapping-key-order `In the representation model, mapping keys do not have an order. ...`
- https://yaml.org/spec/1.2.1/#mapping// `The content of a mapping node is an unordered set of key: value node pairs, with the restriction that each of the keys is unique.`

### Json
- https://www.rfc-editor.org/rfc/rfc8259.html `An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.`

In our code base, one would need to examine how swagger-parser loads in json and yaml spec files and see if it preserved key order.

So the specs for these formats do not require preserving the order of the key value pairs.
Because of that, in my opinion all object (dictionary) model arguments should probably be passed in using named arguments.
