### ISSUE TITLE
[REQ] [SWIFT] Add ability to provide a custom ResponseSerializer 

### ISSUE THREAD

**Issue by cerupcat** [OpenAPITools/openapi-generator#11629]
### Is your feature request related to a problem? Please describe.

Alamofire defaults emptyResponseCodes to [204, 205], however, our server supports 200 too. Therefore, 200 empty responses fail validation.

## Describe the solution you'd like

Allow passing in a customResponseSerializer to provide more customization to responses

**Comment by Jonas1893** [comment]
I also have this issue. I am wondering whether we really need the full customization abilities of custom response serializers. Because we would need to add an injection point for a custom response serializer for each response type which is quite a lot. However what is only needed to solve this specific problem is to be able to inject the empty response codes for the Void type which could just be a new property on AlamofireRequestBuilder

**Comment by JonnyBeeGod** [comment]
Hi @4brunu how do we proceed with this ticket? I think we can close it

**Comment by 4brunu** [comment]
I think we can close it. In case any issue appears, please open another issue. Thanks
