### ISSUE TITLE
[REQ] [Swift] Abstract away URLSession

### ISSUE THREAD

**Issue by Czajnikowski** [OpenAPITools/openapi-generator#11651]
### Is your feature request related to a problem? Please describe.

Yes. I'm trying to implement a caching mechanism that basically overrides the `URLSession.dataTask` and under the hood it takes the response from the cache (if available) and at the same time loads using the `URLSession` itself. Currently, the only way of changing the `URLSession` is via override of `URLSessionRequestBuilder.createURLSession` (well, I can always write my own `RequestBuilder`, but that'd be a lot of duplicated code). So to be able to implement my approach I'd have to subclass `URLSession` and override the `dataTask`.

The implementation would look like this:
```swift
class CacheFirstURLSession: URLSession {
    override func dataTask(
        with request: URLRequest,
        completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void
    ) -> URLSessionDataTask {
        if let cachedResponse = configuration.urlCache?.cachedResponse(for: request) {
            completionHandler(cachedResponse.data, cachedResponse.response, nil)
        }

        return super.dataTask(with: request, completionHandler: completionHandler)
    }
}
```

This is not currently doable (as far as I know, `URLSession`s are not subclassable). I tried a couple of times to make a subclass, but it does not work - calling `dataTask` crashes the app. Probably because there's no way to inject configuration into a subclass.

## Describe the solution you'd like

So I don't necessarily need a subclass of the `URLSession`, I can go with a wrapper like :
```swift
class URLSessionWrapper {
    private let wrapped: URLSession
    
    init(with wrapped: URLSession) {
        self.wrapped = wrapped
    }
}

extension URLSessionWrapper: DataTaskMaking {
    func dataTask(
        with request: URLRequest,
        completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void
    ) -> URLSessionDataTask {
        if let cachedResponse = wrapped.configuration.urlCache?.cachedResponse(for: request) {
            completionHandler(cachedResponse.data, cachedResponse.response, nil)
        }

        return wrapped.dataTask(with: request, completionHandler: completionHandler)
    }
}
```

The only problem that I have now is that the `URLSessionRequestBuilder.createURLSession` returns the exact `URLSession`. If we'd be able to exchange it into a protocol then my problem is solved.

Here's an initial idea of what we'd have to do in the `URLSessionImplementation.mustache`:

Somewhere at the top (or bottom):
```swift
public protocol DataTaskMaking {
    func dataTask(
        with request: URLRequest,
        completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void
    ) -> URLSessionDataTask
}

extension URLSession: DataTaskMaking {}
```

And then change the override:
```
{...} func createURLSession() -> DataTaskMaking {
    return defaultURLSession
}
```

## Describe alternatives you've considered

So I tried solving the problem with subclassing and extensions which both don't seem to be feasible in our current architecture. Another possible option is to create my own own `RequestBuilder`, but that'd be a lot of duplicated code.

## Additional context

Nope

**Comment by leszek-s** [comment]
Yes, abstracting URLSession with a protocol as proposed by @Czajnikowski would be super useful not only for implementing caching as proposed here but also for other stuff such as mocking for unit tests, adding semaphores or some kind of other mechanism to limit the number of request executed at the same time, adding logs, adding some additional headers only to specific requests and generally that would give much more flexibility to existing templates for people who need that flexibility. I'm experimenting with openapi generator since few days because I plan to use it in next project and that URLSession abstraction would greatly simplify a lot of stuff for me. Without this abstraction currently lots of stuff seems to be very inconvenient to implement and would require duplicating and overriding a lot code from current template or using custom modified template. This URLSession abstraction would be a massive improvement and it seems that it would not require many changes in the code. @4brunu is there any chance that this can be added to swift5 template?

**Comment by 4brunu** [comment]
Hey,
This is already possible today.
You need to subclass `URLSessionRequestBuilder` and `URLSessionDecodableRequestBuilder` and you override the method `createURLSession` to return your desire subclass of `URLSession`.

Here is an example of subclassing `URLSessionRequestBuilder` and `URLSessionDecodableRequestBuilder`.

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/swift5/urlsessionLibrary/SwaggerClientTests/SwaggerClient/BearerDecodableRequestBuilder.swift

If you do this you have a lot of customisation available, but it's not well documented, I learned it by exploring the code and implement some things like you are requesting.

By overriding the method `createURLSession` you can use your own subclass of URLSession.

By overriding the method `execute` you can control what happens before each request is executed, avoid that it executes, return a cached response, etc. 

Hope that it helps.

**Comment by leszek-s** [comment]
Hello @4brunu, I saw that example in `BearerDecodableRequestBuilder.swift` and yes that works for implementing token refreshing but still subclassing URLSession would be better but unfortunately it is not possible. As @Czajnikowski wrote subclassing `func dataTask(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask` crashes the app with SIGABORT error. I think it was possible to subclass URLSession some time ago but currently it is not working I just checked with this code which always crashes on call to super.dataTask:
```
class MyURLSession: URLSession {
    static let defaultUrlSession = MyURLSession()
    override func dataTask(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask {
        return super.dataTask(with: request, completionHandler: completionHandler)
    }
}
```
and
```
    override func createURLSession() -> URLSession {
        return MyURLSession.defaultUrlSession
    }
```
It also shows a warning that `'init()' was deprecated in iOS 13.0` next to `MyURLSession()` and if you open URLSession definition you can also see this in Apple's code:
```
    public /*not inherited*/ init(configuration: URLSessionConfiguration)

    public /*not inherited*/ init(configuration: URLSessionConfiguration, delegate: URLSessionDelegate?, delegateQueue queue: OperationQueue?)
```
So it is currently not possible to properly initialize subclassed URLSession and that explains why it crashes if you try to do that. Therefore without abstracting URLSession replacing it by overriding `createURLSession` is currently not very useful. Also this stack overflow topic confirms problems with subclassing URLSession: https://stackoverflow.com/questions/48158484/subclassing-factory-methods-of-urlsession-in-swift
If instead of URLSession we could provide anything that confirms to a protocol as proposed by @Czajnikowski then that would solve this problem.

**Comment by 4brunu** [comment]
I see the issue.
I'm open to this solution, and will help with the review process, if someone want's to open a PR.

**Comment by 4brunu** [comment]
Could you please open a PR?

**Comment by Czajnikowski** [comment]
Thanks for reviving that thread and for the implementation @leszek-s 🙌

**Comment by leszek-s** [comment]
> Could you please open a PR?

Here is PR: https://github.com/OpenAPITools/openapi-generator/pull/12110

**Comment by 4brunu** [comment]
fixed by https://github.com/OpenAPITools/openapi-generator/pull/12110
