### ISSUE TITLE
[python-experimental] Allow keeping snake_case

### ISSUE THREAD

**Issue by MalteEbner** [OpenAPITools/openapi-generator#12121]
## Requested feature

I want to switch to python experimental to generate a python client:
```
npm install -g @openapitools/openapi-generator-cli
openapi-generator-cli version-manager set 6.0.0-beta

openapi-generator-cli generate -i $PATH_TO_SPEC -g python-experimental -c config.yml
```

However, this generates camelCase identifiers instead of snake_case. This makes it harder to switch from the old python generator. Is it possible to pass an argument to use snake_case instead?

## What I tried:
In the `config.yml`, I added
```
additionalProperties:
  identifierNamingConvention: snake_case
```
It had no effect.

I had also tried adding `--additional-properties="_spec_property_naming=False"` and `--additional-properties=identifierNamingConvention=snake_case` to the CLI command, no effect.

**Comment by spacether** [comment]
Keeping snake case is a problem because in one schema camelCase is present and one could convert to camel_case but in another schema camelCase would be an additional property and the code would not know to use snake case.

Also one can ingest camelCase and camel_case as different properties in the same dict. We need to support that use case by keeping spec case.

**Comment by MalteEbner** [comment]
Thank you @spacether for outlining this reasoning!
