### ISSUE TITLE
[BUG][typescript-fetch] New FetchError class incorrectly extends base class Error

### ISSUE THREAD

**Issue by sevein** [OpenAPITools/openapi-generator#12927]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

https://github.com/OpenAPITools/openapi-generator/commit/3a2bbbb8501f7238dba0dc124234e9e0459cdd9e introduced a new class (FetchError) that produces a build issue in TypeScript when using the strict mode:

```
src/openapi-generator/runtime.ts:239:14 - error TS2415: Class 'FetchError' incorrectly extends base class 'Error'.
  Types of property 'cause' are incompatible.
    Type 'unknown' is not assignable to type 'Error | undefined'.

239 export class FetchError extends Error {
                 ~~~~~~~~~~
```

Example of FetchError:

https://github.com/OpenAPITools/openapi-generator/blob/8d62e597ae6cd463b5c203a9662643dc839bfec0/samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts#L239-L244

##### openapi-generator version

v6.0.1 (and master)

##### OpenAPI declaration file content or url

N/A

##### Generation Details

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

FetchError was introduced in the context of this issue: https://github.com/OpenAPITools/openapi-generator/pull/12716.

##### Suggest a fix

N/A

**Comment by sevein** [comment]
Hey @orange-buffalo, since you designed FetchError I was wondering if you can think of a solution. Thank you in advance!

**Comment by ssuchkov** [comment]
I had this very issue because I had `"esnext"` lib in `tsconfig.json`
Since lib.es2022.error.d.ts brings `interface Error {cause?: Error}` it considered to be overridden in incorrect way. 

Removing `"esnext"` fixed the issue for now.

**Comment by orange-buffalo** [comment]
Th current code for `FetchError` is the following:
```typescript
export class FetchError extends Error {
    name: "FetchError" = "FetchError";
    constructor(public cause: unknown, msg?: string) {
        super(msg);
    }
}
```
As far as I can see, it is compliant with ES5 definition:
```typescript
interface Error {
    name: string;
    message: string;
    stack?: string;
}
```
(probably this is the reason I missed it during implementation, as I transpile to ES5).

However, in newer versions the definition changes:
```typescript
interface Error {
    cause?: Error;
}
```
Which seems to be clashing with `FetchError.cause`. 

My suggestion would be to align `FetchError` with latest ES. As the very minimum, `cause` should be changed from `unknown` to `Error`. Maybe, the order of parameters could be also changed to be in-sync with new `Error` constructor: `new (message?: string, options?: ErrorOptions): Error`. 
Formally it breaks backwards compatibility, since `FetchError` is a public class. One could argue that this is fine since we are fixing a bug in the first place. 

CC @macjohnny

**Comment by macjohnny** [comment]
@orange-buffalo can you file a PR?

**Comment by orange-buffalo** [comment]
#13004. I decided to go with the minimal changes. Checked the samples build with es5 and esnext, both passed.
