### ISSUE TITLE
Spring code generator support for useRuntimeException flag

### ISSUE THREAD

**Issue by kester-tt** [OpenAPITools/openapi-generator#1311]
##### Description

ApiException.java generation does not take in account useRuntimeException flag.
Embedded swagger code generator files are affected.

##### Steps to reproduce

Regular `mvn clean generate-sources`

*Expected result:*
```public class ApiException extends RuntimeException {...}```

*Actual result:*
```public class ApiException extends Exception {...}```

##### Related issues/PRs
Duplicate fix from swagger project: https://github.com/swagger-api/swagger-codegen/issues/8789

##### Suggest a fix/enhancement
```
diff --git a/modules/swagger-codegen/src/main/resources/JavaSpring/apiException.mustache b/modules/swagger-codegen/src/main/resources/JavaSpring/apiException.mustache
index f61611477..c752b15c1 100644
--- a/modules/swagger-codegen/src/main/resources/JavaSpring/apiException.mustache
+++ b/modules/swagger-codegen/src/main/resources/JavaSpring/apiException.mustache
@@ -1,7 +1,7 @@
 package {{apiPackage}};
 
 {{>generatedAnnotation}}
-public class ApiException extends Exception{
+public class ApiException extends{{#useRuntimeException}} RuntimeException {{/useRuntimeException}}{{^useRuntimeException}} Exception {{/useRuntimeException}} {
     private int code;
     public ApiException (int code, String msg) {
         super(msg);

```

**UPDATE**
Found that _ApiException.java_ was excluded from default fileset generated by SpringCodegen. Nevertheless having generic API exception is useful, despite it is not referenced in generated code.
Suggest to generate ApiException.java only in case if useRuntimeException was explicitly set.

**Comment by cbornet** [comment]
I'm against adding yet another flag.
I think we should just remove this class from generation:
* it's not used by the other code that we generate. So it might just end as dead code.
* Spring already has a `ResponseStatusException` that does exactly that and is a RuntimeException
* Generating a checked exception was a smell from the beginning. In Spring, for controllers, it's better to throw runtime exceptions and catch them globally with an exception translator.
* Removing the class would be breaking-with-fallback since people can just recreate the class by themselves.

**Comment by kester-tt** [comment]
@cbornet fully agree, was confused by the code and templates from swagger project. Closing the issue. Thanks.

**Comment by cbornet** [comment]
@kester-tt would you do a PR to remove `ApiException` ?

**Comment by kester-tt** [comment]
@cbornet yes, will check it
