### ISSUE TITLE
[REQ] add support for decimals in the python generator

### ISSUE THREAD

**Issue by rizwansaeed** [OpenAPITools/openapi-generator#13324]
## Describe the solution you'd like

Add support to the `python` generator for the following:
```
units:
  type: string
  format: decimal
```
which would generate a field of type `decimal.Decimal` that is de/serialized across the wire as a string.

I am aware that support has been added to the `python-experimental` as part of https://github.com/OpenAPITools/openapi-generator/pull/11282 but we are looking for support in the `python` generator.

## Additional context

We'd be happy to raise a PR but are looking for a steer on what the required changes would be and how long it might take to implement.

Thanks

**Comment by spacether** [comment]
one could maybe add it by changing the mapping for its type to Decimal, but how would it interact with over validation where the type could be plain string with no formatting?
Python-experimental handles those use cases much more elegantly. Just curious, why do you prefer the python client over the python-experimental one? It has the feature that you are looking for, Have you tried it?

**Comment by rizwansaeed** [comment]
I was thinking to essentially do as you say such that the `openapi_types` mapping in the generated model class maps to a `Decimal`. So `type: string` maps to `str` and `type: string, format: decimal` maps to `Decimal`.

For the use case you describe where no formatting is given, it would be treated as a string.

If that sounds like a reasonable approach, we're looking for some guidance as to what code changes would need to be made.

Wrt `python-experimental`, we use the generated SDK in a production environment and so the "experimental" tag led us to believe it wasn't quite finished. Is that that the case or are there still more features that need adding? We'd be open to helping close any gaps if that is the case.

Thanks

**Comment by spacether** [comment]
Experimental refers to the fact that it has been out for a shorter period of time and that we allow breaking changes to be made to that generator. If you version pin you should be fine. It has many more features than the python generator including
- decimal support
- type hints everywhere
- multiple request and response content type handling
- more robust openapi unit testing
Please give it a try and let me know if it meets your needs.

**Comment by rizwansaeed** [comment]
thanks, will give a try and revert back 👍

**Comment by spacether** [comment]
Glad to hear it. If you use the latest master branch there are a ton of type hint improvements and it works great in pycharm.

These are the latest improvements:
https://github.com/OpenAPITools/openapi-generatorhttps://github.com/OpenAPITools/openapi-generator/pull/13325  https://github.com/OpenAPITools/openapi-generatorhttps://github.com/OpenAPITools/openapi-generator/pull/13323  https://github.com/OpenAPITools/openapi-generatorhttps://github.com/OpenAPITools/openapi-generator/pull/13314  https://github.com/OpenAPITools/openapi-generatorhttps://github.com/OpenAPITools/openapi-generator/pull/13309  https://github.com/OpenAPITools/openapi-generatorhttps://github.com/OpenAPITools/openapi-generator/pull/13299  https://github.com/OpenAPITools/openapi-generatorhttps://github.com/OpenAPITools/openapi-generator/pull/13271

**Comment by rizwansaeed** [comment]
Hi Justin,

I've had a try with the python-experimental generator. There seems to be a number of breaking changes between the it and the python one (which are reasonable and I suppose expected), but this does mean that adoption would take us longer to complete.

I did manage to almost get a couple of calls working but we've hit a blocking issue:

```
NotImplementedError: Serialization has not yet been implemented for application/json-patch+json
```

So for now at least we are probably going to need to try to add the feature into the existing python one. Would you be able to provide some guidance as where in the generator code we would need to make the changes?

Thanks

**Comment by spacether** [comment]
Hi there, I just fixed your blocking issue in [this PR](https://github.com/OpenAPITools/openapi-generator/pull/13356) which has been merged into master branch.
[This test](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/tests_manual/test_fake_api.py#L730) verifies that json patch serialization and sending is working and it [passed in CI here](https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/19391/workflows/75be2431-2f5f-4a61-8107-4868f3f924e6/jobs/48451).
So my suggestion is to use python-experimental because:
- it now has the features that you need
- updating your code with the needed changes migrating from the old python generator will probably take more time than writing a PR adding decimal to the python generator
- the python generator needs all value stored for a location to be the same. if there are two allOf schemas that constrain the value and one defines a decimal as `type: string` and another defines it as `type: string format: decimal` I do not think that it will work in the `python` generator. That definitely will work in the python-experimental generator.

If you do want to move forward with a PR in the `python` generator then these are some places that will need to change (from looking at how datetime is done):
- Decimal will need to be added to the AnyType type string generation here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java#L864
- and here https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java#L892
- You will need to add a `typeMapping.put("decimal", "decimal.Decimal");`
- You will need to update sanitize_for_serialization, get_simple_class, COERCIBLE_TYPE_PAIRS in the python templates to handle Decimal inputs
- Update many more locations in the python templates, look at where datetime and date are used, and add Decimal handling

**Comment by rizwansaeed** [comment]
Thanks for fixing that so quickly, I'll take a look at the experimental and python changes

**Comment by spacether** [comment]
closing this because the feature exists in python-experimental

**Comment by spacether** [comment]
my mistake re-opening this

**Comment by spacether** [comment]
Closing this because the current python generator in v6.2.0 and onward supports decimals
