### ISSUE TITLE
[REQ] New typescript-generator option to set file extension for ECMAScript module resolution

### ISSUE THREAD

**Issue by danmichaelo** [OpenAPITools/openapi-generator#14333]
### Is your feature request related to a problem? Please describe.

I'm trying to generate a pure ESM package (`type: "module"`) using [ESM in Node.js](https://www.typescriptlang.org/docs/handbook/esm-node.html), but the Typescript generators generate relative imports without file extensions (e.g. `import * as runtime from "../runtime"`) while [Node.js requires file extensions for ESM imports](https://nodejs.org/api/esm.html#mandatory-file-extensions) (`import * as runtime from "../runtime.js"`)

## Describe the solution you'd like

* The `typescript` generator already has an internal option `extensionForDeno`, which is set to `.ts` when `platform` is `deno`. I suggest renaming `extensionForDeno` to `importFileExtension` and making it a public option.
* The other typescript generators does not have such an option, so it may have to be added to those, if needed

I can try putting together a PR for this, but would like to gather some feedback about whether it's a good idea first.

## Describe alternatives you've considered

* <s>It's possible to generate a valid ESM package by setting `moduleResolution: "node"` (CommonJS for internal module resolution) and `module: "ESNext"`, but this will fail if we add additional dependencies to the generated package that aren't CommonJS compatible.</s>

* Instead of adding a new option `importFileExtension`, derive the file extension from some other option:
  * From `platform`? If we add a new value like `node-esm`. The problem is that there are several different extensions that can potentially be used (`.js`, `.mjs`, `.tjs` etc.) and users may have different preferences.
  * Perhaps a new option `moduleResolution` with values `node` and `node16` inspired by TypeScript?

**Comment by stefanpl** [comment]
Hi @danmichaelo (and a Happy New Year 🎉),

I'm currently facing the same issue. `importFileExtension` as a public option sounds straightforward to me from a DX perspective 👍

My understanding was that the `typescript` generator is meant to focus all TS-related efforts, so adding it there should probably be the main goal. Until this lands, I'll post our current workaround for `typescript-fetch` below.

**Comment by stefanpl** [comment]
Our team's current workaround for the **`typescript-fetch`** generator (which we're using since `typescript` is still flagged "experimental"):
- we're using `npx fix-esm-import-path generated/dir` to add the extension to the generated files.
- the only thing not catched by this is the `import type ... from '../models'`, so we slightly changed that with a [modified template](https://openapi-generator.tech/docs/templating/#modifying-templates) (touching only `apis.mustache`, and `sagas.mustache` if need be):
```diff
-} from '../models';
+} from '../models/index';
```

Until `importFileExtension` (or a similar mechanism) has landed in `typescript`, I'd very much like to merge the changed model import in `typescript-fetch`. In case there's no objections, I'll open a small PR.

**Comment by danmichaelo** [comment]
Thanks @stefanpl – and happy new year ✨ 

`npx fix-esm-import-path` was neat – I wasn't aware of that one! 

I put together a PR for `typescript` to start with, but we're also using `typescript-fetch` at the moment, so perhaps I'll try to put together a second PR for that if the first is accepted.
