### ISSUE TITLE
ApiUtil class does not support UTF-8 response by default.

### ISSUE THREAD

**Issue by FutureGadget** [OpenAPITools/openapi-generator#1463]
##### Description

ApiUtil class does not support UTF-8 response by default.

##### openapi-generator version

3.3.0

##### Command line used for generation

openapi-generator generate -i {filename} -g spring

##### Steps to reproduce

1. write a spec including utf-8 chars in the response example

2. generate spiring code using the command
`openapi-generator generate -i {filename} -g spring`

3. Run the spinrg application and test the API generated by the openapi-generator
by requesting through swagger-ui web page.

4. The response will be 500 error, and you will get the Caused by: java.io.CharConversionException: Not an ISO 8859-1 character: [거]
( "거" is the utf-8 character(Korean) that caused this problem )

##### Suggest a fix/enhancement

The generated code in the ApiUtil.java should be modified as follows:
Before:
```
public static void setExampleResponse(NativeWebRequest req, String contentType, String example) {
        try {
            req.getNativeResponse(HttpServletResponse.class).addHeader("Content-Type", contentType);
            req.getNativeResponse(HttpServletResponse.class).getOutputStream().print(example);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

After:
```
public static void setExampleResponse(NativeWebRequest req, String contentType, String example) {
        try {
            req.getNativeResponse(HttpServletResponse.class).addHeader("Content-Type", contentType);
            req.getNativeResponse(HttpServletResponse.class).getWriter().print(example);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by wing328** [comment]
@FutureGadget thanks for reporting the issue. Can you file a PR so that we can review the change more easily?

Also please share the spec to reproduce the issue.

We do have test cases to cover double-byte characters but clearly it didn't catch the issue you mentioned so we probably need to update it to extend the coverage: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml#L692
