### ISSUE TITLE
[BUG] [Java/spring] OpenApi generater doesn't wrap sort as a request parameter

### ISSUE THREAD

**Issue by Kavan72** [OpenAPITools/openapi-generator#14651]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

Description

I am trying to use `sort` parameter as a query parameter in my OpenAPI specification, but if we use object in query parameter on that time generator not generating proper code. here is my swagger file [swagger.yaml](https://gist.githubusercontent.com/Kavan72/33b4357edc394e97aef7f878935a2356/raw/667991b218c12a0e96580f7fcef0b6a60cfe3e5d/query-parameter-bug-swagger.yaml)

I'm using latest version on openapi-generator and spring boot
```
openapi-generator version : 6.3.0
spring-boot : 3.0.2
```

##### OpenAPI declaration file content or url

Here is my definition of OpenAPI endpoint

```yaml
/test:
    get:
      tags:
        - story
      summary: get all from database
      description: get all the story
      operationId: get-all
      parameters:
        - in: header
          name: Language-Code
          schema:
            type: string
          required: true
        - name: sort
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Sort'
        - name: columns
          in: query
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Column'
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
components:
   schemas:
       Sort:
           properties:
              columnName:
                  type: string
              sortType:
                  type: string
                  enum:
                      - ASC
                      - DESC
```
 
Generation Details

And here is my generated code, in this code, 'sort' parameter is not wrapping with @Requestparam

```Java
@RequestMapping(
        method = RequestMethod.GET,
        value = "/test",
        produces = { "application/json" }
    )
    default ResponseEntity<RestGetAll200Response> getAll(
        @NotNull @Parameter(name = "Language-Code", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "Language-Code", required = true) String languageCode,
        @NotNull @Parameter(name = "sort", description = "", required = true, in = ParameterIn.QUERY) @Valid RestSort sort,
        @NotNull @Parameter(name = "columns", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "columns", required = true) List<RestColumn> columns,
        @NotNull @Parameter(name = "page", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = true) Integer page,
        @NotNull @Parameter(name = "pageSize", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize,
```

**Comment by borsch** [comment]
@Kavan72 it's not required in this case. `sort` is a model and not a primitive type

check for more info here http://dolszewski.com/spring/how-to-bind-requestparam-to-object/

**Comment by borsch** [comment]
Why do you expect `@RequestParam` here?

**Comment by borsch** [comment]
@Kavan72 could you please share minimal reproducible example?

**Comment by Kavan72** [comment]
@borsch sure, i've uploaded minimal code [here](https://github.com/Kavan72/query-parameter-bug-spring-boot), also uploaded curl cmd to test api

**Comment by Kavan72** [comment]
@borsch did you get a chance to look at it?

**Comment by borsch** [comment]
@Kavan72 sorry for delay. Finally got what you would like to add. As for now this is not supported. Current template doesn't add `@RequestParam` if object is model which. Note `{{^isModel}}@RequestParam .. {{/isModel}}`

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/queryParams.mustache


My proposition for workaround - you can use custom templates to customize `queryParasm.mustache` so that `@RequestParam` would always be there. I've created PR to your repo with required changes https://github.com/Kavan72/query-parameter-bug-spring-boot/pull/1/files

**PS:** please note that this template update might break something for other parameters where `@RequestParam` annotation isn't expected

**Comment by Kavan72** [comment]
@borsch thank you so much for creating a pr. does it's a bug or something which is not supported by openapi ?

**Comment by borsch** [comment]
@Kavan72 it's rather not supported by Spring. In your case `RestSort` got two properties `columnName` & `sort`. When such models added to controller method, Spring handle them in the following way `/test?columnName=abc&sort=ASC`. Kind of flat object. That's the reason why generator don't add `@RequestParam` to models, because it assumes that object is just a set of properties(request parameters) that should be used together

**Comment by borsch** [comment]
@Kavan72 could you please close the issue if you don't have any further questions?

**Comment by Kavan72** [comment]
sure @borsch thank you for help
