### ISSUE TITLE
[Feature][Go][Ability to specify different field name than JSON derived one

### ISSUE THREAD

**Issue by wtrocki** [OpenAPITools/openapi-generator#15002]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Golang has an internal linting rule that forces users to use strict naming schemes for some of the properties.
For example, ID property is preferred over Id. 

Generated golang client doesn't meet those as it is based on the exact property names.

Examples: 
https://github.com/golang/lint/blob/master/lint.go#LL770-L809
https://github.com/mgechev/revive/blob/b03e54f617491984b41f0411b69326f94d03a76f/lint/utils.go#L89-L128

##### openapi-generator version

master 

##### OpenAPI declaration file content or url

```yaml
    properties:
       id:
          type: string
          description: id
```

Generates `Id` struct property where in go typically this would be `ID`.

##### Steps to reproduce

Generate client that has id field. 

##### Suggest a fix

Enable: `x-codegen-name` extension to rename field in openapi without affecting json value.

**Comment by wing328** [comment]
Personally i don't prefer such solution as the same `x-codegen-name` won't work across different generators (in other words, we may need something like `x-java-codegen-name`, `x-go-codegen-name`, which is again not something i prefer)

What about a mapping (e.g. id => ID) to specify how these special words should be handled so that each generator (when executed via openapi-generator-cli for example) can have complete control on how names (parameters, properties, etc) are constructed to meet the language-specified guideline?

**Comment by wtrocki** [comment]
See now that there is `reservedWordsMappings` functionality that does achieve that already.
