### ISSUE TITLE
[BUG][CLIENT][JAVA] artifactVersion is not taken from specification

### ISSUE THREAD

**Issue by mindhaq** [OpenAPITools/openapi-generator#1815]
##### Description

When the options for the generator do not provide `artifactVersion`, in the generated `pom.xml`, the `<version>` is always `1.0.0`. It should be the version provided in the openapi specification file.

##### openapi-generator version

3.3.4

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  title: Title
  description: Description
  version: "1.2.0"
```

##### Command line used for generation

```
openapi-generator generate \
    --input-spec ./spec.yml \
    --output ${outdir} \
    --generator-name java \
    --config config.client-java.json \
    --enable-post-process-file \
    --group-id com.minhdaq \
    --artifact-id project
```

```json
{
  "java8": true,
  "dateLibrary": "java8",
  "useBeanValidation": true,
  "library": "resttemplate",
}
```

##### Steps to reproduce

Create an API with version information. Find 1.0.0 instead of that version in the pom.xml.

##### Suggest a fix

Use version from YML in pom.xml.

**Comment by karismann** [comment]
i thought that #2033 would fixed this problem but in fact it doesn't because `this.openAPI` used in this fix isn't yet set in `processOpts` methods (see https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java#L188)
@wing328  what do you think if we set `DefaultGenerator.openAPI` juste before `processOpts` call in `DefaultGenerator` to allow use of `this.openAPI` in extended `processOpts`  method to fix this ?
that would also fixed #2019 who doesn't work neither for typescript
