### ISSUE TITLE
[BUG] [JetBrains] Query parameters missing

### ISSUE THREAD

**Issue by stevium** [OpenAPITools/openapi-generator#18244]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Query parameters are missing from generated URLs although they are present in the YAML parameters declaration.

##### openapi-generator version

7.4.0

##### OpenAPI declaration file content or url

https://api.opendota.com/api

##### Generation Details

`openapi-generator generate -i https://api.opendota.com/api -g jetbrains-http-client -o dotaClient`

##### Steps to reproduce

1. Execute the provided generation command
2. Notice that query parameters are missing from generated URLs (`?param1={{param1}}&param2={{param2}}&param3={{param3}}`...) 

##### Suggest a fix

Don't have a fix proposal, but in general appending the params to the end of URL path is considered one of the very basic functionalities any REST API client should support. All of the other generators already support it.

The generated get request should be in a form of:

`GET https://api.example.com/api/v1/example-endpoint?param1={{param1}}&param2={{param2}}&param3={{param3}}`

instead of:

```
GET https://api.example.com/api/v1/example-endpoint
```

**Comment by wing328** [comment]
thanks for reporting the issue

cc @jlengrand

**Comment by jlengrand** [comment]
See https://github.com/OpenAPITools/openapi-generator/issues/18035 for context. I will continue in this issue from now on

**Comment by jlengrand** [comment]
Ok @stevium , finally picking this one up. Do you have an opinion of how this should be implemented?

I'm asking because required parameters should be possible to integrate, with a required variable.
What about optional parameters though? Inserting all possible params will pollute the query and also make it impossible to run without filling in all values. What do you think?

For example, in the request you are presenting the parameter is optional, meaning the query can actually run without it. No sensible default is indicated in the schema either, meaning I cannot use a default value.

I see several potential ways forward:

* Implement the logic for required query params, but that means nothing will change in your specific case
* Implement the logic for all params, with a variable for each param. This will add a lot of potential overhead for complex APIs with a lot of parameters available.
* Implement logic to at least indicate which query parameters are available in the comments, so they can easily be added to the query by the user.
* I also thought about multiplying the operations, to have one with / without parameters, but this will create confusion and doesn't seem very user friendly, on top of potentially not being correct for mutually exclusive parameters.

One more thought regarding query parameters is that they will tend to be used in many requests. For example, {{size}} will most likely be used for pagination in all requests. Meaning that using a variable for this leaves us with two choices : 
* Have the same {{size}} for all requests by default
* Have one variable per request
 
All those options can be controlled to a certain extent via option flags.

Other ideas?

**Comment by jlengrand** [comment]
@stevium , I've implemented header and query params in this PR, care to try it ? https://github.com/OpenAPITools/openapi-generator/pull/18844
