### ISSUE TITLE
[REQ] Bare boned git for custom generator creation

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [OpenAPITools/openapi-generator#1898]
Introduction:
As it was mentioned by @jimschubert in #1894 it is possible to create a new generator which is not embedded into the core module. For that the generator can create a template which can be changed and edited into a new custom generator unknown to everybody in the wild wild world: My intention is to simplify this procedure and to make it easier for everyone out there to find other custom generators and to prevent duplicate repositories doing the same but being implemented by different developers. My final goal is to help with this template to remove every single generator from the core module so that every single generator must be loaded individually, may it be via gradle/maven or via webapi where I can download new custom generators via a new download-module in the main generator.
Short summary:
- everything which could be a module should be a module

Why do I really want this feature?
Custom generators as the status quo and only allowed generator in general would make a generator more open and editable and easier to customise for production usage (example: The Haskell client generator generates a module which does not need to be edited by hand in any case. Mock servers can be written in meta modules keeping the generated code clean. But I need to serve static files which is not supported by the generator so I had to modify the generator by myself to keep the generated code clean and to keep every project the same). The big problem I am having with small changes on those embedded generators: I need to merge every single commit into my changed codebase to be on the bleeding edge and to get other improvements or bug fixes.
If I would only have edited a module generator I had no work on updating my changes to keep being on top of the commit stack.
Short summary:
- individual changes to single code generator are a heck easier to maintain
- a wider range of code generators
- It is easier to get my custom code generator into the community
- not any longer maintained generators can easily be cloned and replaced
- I have not a handful of lead-developers who can decide on what will be known and what not or which feature will be included into the generator
- Keeping the core-code-base clean. When I looked at first into the project to fix a bug in the python generator I was disgust by the missing structure, the immense amount of redundant code, the heck of a load possible null pointers (null safety and java. Not a good mix) that I thought of not creating a bug report or a pull request because I had no longer any interest in contributing to this project.

What is the intention of a git template?
The Idea of the git template is to provide code formatters (I would suggest Java and Kotlin and Scala (personal problem with groovy: It is not typesafe. I hate everything which is not type safe and I see no point in supporting a lacking compile time safety) and perhaps groovy and other JVM languages). The easiest would be to support that wide range to use a bould tool like gradle or bower, but maven would be working, too. Also there should be the default files like contribution guide, code of conduct, license (which allows the cloning and editing of the project if it is public available, permits to change the license and guarantees that the generated code is completely under custom license without restriction).

What for files hould be in the template (at least):
- Code formatter configurations (not bound on any IDE. The code formatters have to work with the build tool (mvn, gradle, bower)
- checkstyle for java and the equivalent for kotlin and scala if available
- full functioning build tool configuration (mvn, gradle, bower).
- README.md- LICENSE.md
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md 
- .gitignore
- .gitattributes
- directory with build server configurations like:;
    - .travis
    - jenkins
    - circleci
- directory .github with all the default github files
- bin directory with fancy shell scripts (can be empty with .gitkeep file)
- example directory containing a compiled version of petstore so every user can see a generated code sample and is able to compare different generators
- doc directory where the programmer should document every custom property or default properties that are not supported.

**Comment by jimschubert** [comment]
Thanks for the suggested feature request. I like the idea of trying to make this use case of OpenAPI Generator a little less intimidating. However, I think the full list of suggestions would greatly increase the maintenance footprint for the core team and/or the community. I'll explain, then end with a few suggestions.

We already offer a `meta` generator, which outputs the bare minimum of files required for creating a custom template. You can see an example of the output under [samples/meta-codegen/lib](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/meta-codegen/lib) and an example of usage at [samples/meta-codegen/usage](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/meta-codegen/usage).

While I think that most of the other files listed above make sense to include in an open source project (I create most of them for every new project), I would question whether some of them belong in the meta generator. We don't include most of these files in other generators (with reasons):

* checkstyle configurations
  - style is a very personal thing, or strict per-team
  - not everyone uses (or even likes) checkstyle
* `CONTRIBUTING.md` or `CODE_OF_CONDUCT.md`
  - These would have to be very generic, and would need to be modified by the user
* `LICENSE.md`
  - We wouldn't know what to put in here
  - side note: I think OSS standard is no extension… `LICENSE`
* `.github`, `.gitignore`, `.gitattributes`
  - These assume generated code will be distributed via Git, which -although probably accurate- can't be assumed
  - We would inevitably end up maintaining files for other VCS, which most of the community probably doesn't have enough experience to maintain
  - GitHub offers defaults for the `.github` directory when you go to a repository's "Settings"
* Build server configurations
  - These are personal preference
  - Why not include GitLab CI, GitHub Actions, etc.?
  - If the directory is named `build`, and we were to output Gradle files, this could cause conflict, so I'd recommend `.build` as a naming convention
* `bin` directory
  - Do we assume bash, zsh, or fish? If so, why?
  - Some people (like me) may build certain projects in an alpine container, which doesn't include `bash` by default, so would pure `sh` be sufficient?
  - We support windows users, so we'd probably want to include batch files (or even powershell)
  - `bin` is sometimes used to indicate a runnable for the current project; I'd suggest `scripts` or `.scripts`
* > example directory
  - We already have this under [samples/meta-codegen/usage](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/meta-codegen/usage)

With most of the suggested files above, I feel like they would add value to a user if they were either empty files or nearly empty ("shells" of a file). Some of these may not add enough value to a user to warrant a custom barebones repository.  For example, suppose you generated code from the `meta` generator, you could easily change into the directory and run:

```bash
mkdir {bin,docs,.github,.build}
touch {LICENSE,CODE_OF_CONDUCT.md,CONTRIBUTING.md}
curl -S https://gitignore.io/api/osx,java,linux,intellij > .gitignore
```

Granted, most of these files would be empty, but I do think users would want these to be lightweight (or templated from their own personal preferences). I can't speak for all users, but as a user myself… I don't like having to modify a bunch of stubbed out text files when I generate code. My personal reason is, for instance, what if I created a generator from this stub for internal use at my employer and I forgot to remove the `LICENSE` file? This could be easily overlooked, and become a legal issue at some places. I tend to use either un-opinionated or very opinionated tools, as these tend to reduce the initial "ramp up" I have when looking threw stubbed code.

All that said, I do agree that we could improve the user experience for generating new generators -- especially for those intended to be shared. I think the best way to go about this would be to update the `meta` generator command, rather than creating a fully separate "starter" repository. There are a few reasons I think this:
* I don't know many engineers who use "starter" repositories… most I know would use something like yeoman to create a new repository or directory structure
* If users wanted to use a "starter" repository, they could use the example from our samples directory
* Since we already offer a way to create a new custom template, creating a separate repository which follows an opinionated structure duplicates maintenance efforts
  - An opinionated structure will lead to many issues/pull requests which question those opinions or attempt to generify those opinions
* The build pipeline would need to be updated to pull, compile, and evaluate the external repository to ensure we haven't broken the public API exposed in its contract
* These concerns would be multiplied for each of the suggested languages

I don't speak for the entire core team here, but I'm hesitant to take on the additional maintenance such a standalone barebones repository would require. 

### Proposal

I'd like to propose the following updates to the `meta` generator based on some of your suggestions, and I wonder if they would satisfy some of your concerns. I think these would improve the `meta` generator while also making the output more open-source-ready.

* include an option for generating Kotlin code
* include an alternative option for Gradle when Java is selected, include only Gradle for Kotlin generated code
* add support for `.openapi-generator-ignore` (for users who are generating into existing directories)
* include opt-in options for each of `CODE_OF_CONDUCT.md`, `CONTRIBUTING.md`, and `LICENSE` (defaulting the contents to the same files from openapi-generator)
* support user-defined templates for all other files

Because we haven't yet separated the execution and templating workflows from the language/framework (i.e. "generator") logic, we can't reuse some of these required workflows outside of the core module. So I think it would be simple to add robustness to the `meta` generator if we moved "meta" generation into the core module rather than using the simplified workflow defined in [Meta](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Meta.java#L76) itself. This gives us reusability of certain features (`CliOption`, user-defined templates, ignore file support, skip-overwrite support, etc.). However, I haven't looked at whether it would add complexity because I know the core generator requires a spec input to be defined.

---
As a side note, I think this feature indicates the need for a tool which users can use to prep a new repository for open source.

**Comment by Fjolnir-Dvorak** [comment]
Hmm, I think I need to wait a bit to see the restructure what it will change. Looking into yeoman seems to be a good Idea. JHipster is based on yeoman and is able to utilize git and to change already modified files.

About support for `.openapi-generator.ignore`: That seems like a huge design failure to me. I should not need to edit generated code, but only extend new files so I am able to regenerate the whole project. At best it would be generated into its own module to separate the generated code even more from my own. A good example where this design pattern failed is the python-flask server where I need to edit the controller files. The problem with adding those to the ignore: All the new features and requests will not be added to the controllers so I am forced to do more or less complicated git magic myself to keep my project up to date and healthy and to be still able to extend my project if I need to.

Answer is still a work in progress

**Comment by Fjolnir-Dvorak** [comment]
As far as I understood the restructuring you have intended this issue will be solved somehow giving enough time for the refactoring to take place.
I would close this issue for now.
