### ISSUE TITLE
[Java][Spring]: Model property description missing for objects

### ISSUE THREAD

**Issue by macjohnny** [OpenAPITools/openapi-generator#219]
##### Description

Model property description is missing if the property is another model object.
With swagger codegen 2.4.0-SNAPSHOT:
```java
public class LogEntry {

  /**
   * Current session of the logged in user when the event occured
   * @return auswertung
  **/
  @ApiModelProperty(value = "Current session of the logged in user when the event occured")

  @Valid

  public Auswertung getAuswertung() {
    return auswertung;
  }

  public void setAuswertung(Auswertung auswertung) {
    this.auswertung = auswertung;
  }
}
```
With openapi-generator 3.0.0:
```java
public class LogEntry {

  /**
   * Get auswertung
   * @return auswertung
  **/
  @ApiModelProperty(value = "")

  @Valid

  public Auswertung getAuswertung() {
    return auswertung;
  }

  public void setAuswertung(Auswertung auswertung) {
    this.auswertung = auswertung;
  }
}
```
##### openapi-generator version

3.0.0

##### OpenAPI declaration file content or url
```yml
definitions:
  Auswertung:
    type: object
    description: 'Auswertung holding information'
    properties:
      auswertungId:
        type: integer
  LogEntry:
      type: object
      properties:
        auswertung:
          type: object
          description: 'Current session of the logged in user when the event occured'
          $ref: '#/definitions/Auswertung'
```

##### Command line used for generation

using maven plugin

**Comment by macjohnny** [comment]
Note: the property description is also missing in the generated `typescript-angular` code:
swagger-codegen 2.4.0-SNAPSHOT:
```typescript
export interface LogEntry { 
    /**
     * Date and time of the event to be logged
     */
    logEntryDate?: string;
    auswertung?: Auswertung;
}
```
openapi-generator 3.0.0:
```typescript

export interface LogEntry { 
    /**
     * Date and time of the event to be logged
     */
    logEntryDate?: string;
    /**
     * Current session of the logged in user when the event occured
     */
    auswertung?: Auswertung;
}
```

**Comment by jmini** [comment]
Your specification is not valid.

Try this in the swagger online editor:

```yaml
swagger: '2.0'
info:
  description: 'Some Decription'
  version: 1.0.0
  title: Test API
host: petstore.swagger.io
basePath: /v2
schemes:
  - http
paths:
  /ping:
    get:
      operationId: opPing
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: Ok
definitions:
  Auswertung:
    type: object
    description: 'Auswertung holding information'
    properties:
      auswertungId:
        type: integer
  LogEntry:
      type: object
      properties:
        auswertung:
          type: object
          description: 'Current session of the logged in user when the event occured'
          $ref: '#/definitions/Auswertung'
```

When you use a `$ref` you are not allowed to set a `description` or a `type`. Swagger Editor now warns you about this: "Sibling values are not allowed alongsite $ref". The Swagger-Parser version we are using now ignores the `description` that you have set when it read the file.
I think that this was not the case in the previous Swagger-Parser Version (used in Swagger-Codegen v2)

It is difficult to argue Swagger-Parser should read the data, because they conform to the spec.

If you construct the OpenAPI instance programmatically (without the Swagger-Parser) and set a description where not allowed, the generated code contains the description (at least last time I checked).

---

For the complete story about this `$ref` stuff (and potential change in the next OpenAPI Specification read this): https://github.com/OAI/OpenAPI-Specification/issues/556 and try to argument. I fully agree with the use-case presented in the issue description, but then you have an on going one discussion about Json-Schema-Spec. I am not sure how this will evolves...

**Comment by macjohnny** [comment]
@jmini thanks for having a look at this. I agree since the yaml is not valid, the openapi-generator correctly handles the specification.

Hopefully [draft-08](https://github.com/OAI/OpenAPI-Specification/issues/556#issuecomment-372431781) will allow to have this feature.

Should we leave this issue open to track this feature or should I close it?
