### ISSUE TITLE
[Discussion] Logo for this project

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#23]
We need a logo for this project... Anyone wants to make a contribution?

**Comment by jmini** [comment]
Here my proposition:
![icon_openapi-generator](https://user-images.githubusercontent.com/1222165/39965485-f5df0a1e-5699-11e8-8ae9-a0294f7a92dc.png)

Some source file icon with an OpenAPI logo.

Feel free to make proposition

**Comment by jimschubert** [comment]
I would suggest against embedding other logos. At lower resolution, this would be almost indistinguishable. For example, load my Intellij plug-in for Swagger Codegen (only one in the plug-in repository) and the .ignore plug-in as well. The file icon for .swagger-codegen-ignore is recognizable while small.

I like OPENAPI Initiative's call out to an interface with the double ended bar. I'm wondering if we could have a similar recognizable design while being unique.

I will try to find time over the next week too work up some designs as well.

**Comment by jimschubert** [comment]
Thoughts on something like this? I apologize ahead of time, it's been a while since I've designed a logo.

I wanted to incorporate something that calls out to the Open API logo with the colors and the interface bar, but also indicate tooling.

![openapitools](https://user-images.githubusercontent.com/109659/40011106-c46f9134-5774-11e8-812f-d99563d6c0dd.png)

**Comment by wing328** [comment]
The last one is the official logo. Thanks @jimschubert for the awesome design.

**Comment by grokify** [comment]
Here is a SVG:

![](http://grokify.github.io/images/logo_openapi-generator.svg)
