### ISSUE TITLE
typescript-angular: Make the api suffix configurable

### ISSUE THREAD

**Issue by macjohnny** [OpenAPITools/openapi-generator#234]
See original issue at https://github.com/swagger-api/swagger-codegen/issues/8281

**Comment by macjohnny** [comment]
@tomvangreen would you like to implement this here at OpenAPI Generator?

**Comment by tomvangreen** [comment]
I have to implement it for swagger codegen, as that is what we use in our project(s) and I cannot change it at this time. But I can see how hard it is to also provide it for openapi-generator. Can't guarantuee anything, but I will see.

**Comment by macjohnny** [comment]
@tomvangreen by the way, migration to openapi-generator is as simple as replacing the dependency in your `pom.xml`:
```xml
<dependency>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>${openapi-generator-version}</version>
</dependency>
```
I did that recently in our project, and it worked like a charm.

I would be happy to review your PR with the changes.

**Comment by tomvangreen** [comment]
I have added two parameters for the typescript angular code generator, serviceSuffix and serviceFileSuffix. I tried running the tests and I get an error, that those two parameters have not been tested. I looked through the repo to try to find out where or how I can test those new parameters, but I am a bit lost.

Can anybody point me in the right direction for this?

**Comment by macjohnny** [comment]
@tomvangreen what is the error message?
@wing328 any idea where to fix this?

**Comment by tomvangreen** [comment]
@macjohnny Sorry, I could have added the message right away. I get this error message:
`Failed tests: 
  TypeScriptAngularClientOptionsTest>AbstractOptionsTest.checkOptionsHelp:61 These options weren't checked: serviceSuffix, serviceFileSuffix.
`

**Comment by tomvangreen** [comment]
I think I got it. I needed to add the parameters in the `TypeScriptAngularClientOptionsProvider`.

**Comment by tomvangreen** [comment]
@macjohnny I think this issue can be closed, as my pull request has been merged. 

But before you close it, maybe I could hijack this issue for another related topic/questsion. One other point of pain for us is the naming of the model classes. The swagger api we are using is also used by other clients and we don't have much control over how the models are tagged/named. 

I was thinking that maybe I could add a configuration option to make the model suffix also configurable (for example, instead of having a file `user.ts` with the class `User`, we could configure the suffix `Vm` and file suffix `.vm` in order to get the file `user.vm.ts` with the class `UserVm`). Do you think a config param like that would make sense? I think in most cases the better solution would probably be to simply give the right name in the swagger schema. 

If there is no objection I could have a look if I can implement that configuration.

**Comment by TiFu** [comment]
Sorry, I have been insanely busy the past couple weeks.

I don't see any problem with adding this option as long as it defaults to not adding a suffix. It might also be useful for other generators even if the model classes are not put into different files.

**Comment by tomvangreen** [comment]
I'm not sure how simple it is to implement this also for the other generators. I only had a look into the typescript angular one, but I see how hard it will be to have this for the other ts generators as well. 

If I can implement the change I will make sure that you will have the same output as before if you don't set the option.

**Comment by macjohnny** [comment]
implemented with https://github.com/OpenAPITools/openapi-generator/pull/418
