### ISSUE TITLE
[BUG] Maven plugin: skipValidateSpec option

### ISSUE THREAD

**Issue by adigerber** [OpenAPITools/openapi-generator#2577]
##### Description

* `skipValidateSpec` affects the wrong option - `skipOverwrite`.
* Why even have `skipValidateSpec` if there's already `validateSpec` which supposedly does the same thing?

##### openapi-generator version

Master branch - 9c7d407

##### Suggest a fix

Remove `skipValidateSpec` completely in favor of `validateSpec`, or change it to call `setValidateSpec` instead of `setSkipOverwrite`.

**Comment by jimschubert** [comment]
the `setSkipOverwrite` issue was fixed via #2583

> Why even have skipValidateSpec if there's already validateSpec which supposedly does the same thing?

`skipValidateSpec` is more desirable here because it aligns configuration across CLI/Gradle/Maven, where we are forced to the truthy option by the CLI's option parser framework (we can't easily or cleanly pass `validateSpec=false`). The option also implicitly conveys that we validate the spec by default.

**Comment by jimschubert** [comment]
see #2614

**Comment by adigerber** [comment]
Thanks for the fixes @jimschubert and sorry for the late response. Closing this.
