### ISSUE TITLE
[typescript-fetch] Documentation / Example Project

### ISSUE THREAD

**Issue by GillesWHC** [OpenAPITools/openapi-generator#2594]
Is there an example or some documentation about the generated typescript-fetch client? I'm really walking around in the dark here. Currently I'm looking at [this project](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-fetch/tests/default/test) for reference.

**Comment by wing328** [comment]
@GillesWHC Are you looking for documentation on how to use the auto-generated TS fetch client?

**Comment by GillesWHC** [comment]
@wing328 Yeah that's exaclty what I'm looking for! Setting everything up went great, but actually using the client is a tad bit harder.

**Comment by djMax** [comment]
The "web" is very confused about this because of the history of swagger in general. If one wants to consume the result of ```openapi-generator generate -i ../my-api-spec.json -g typescript-fetch``` in a "plain" Javascript project, I assume there's a build step. But there is no package.json generated by the generator. What is the workflow to use the client after generation?

**Comment by GillesWHC** [comment]
@djMax I pushed it to my own npm registry using the `--additional-properties npmRepository=YOUR_HOST` flag. Then you're able to install it just like any other package using npm. Make sure to configure npm to use your registry instead of the default one!

**Comment by fuzzzerd** [comment]
After the refactor was merged in to v4, I feel that a lot has changed. The simple parts of using it as a package or copying the files into your own project haven't changed that much. What's I'd love to see is guidance on consuming the generated clients. 

The new `Configuration` options specifically: oauth, bearer, and middleware. I cannot find examples/guidance on that anywhere.

**Comment by monscamus** [comment]
As above I've generated my typescript-fetch API and tsc'ed it into a nice npm package - but I can't find a good example of actually calling the library.

**Comment by JavaJamie** [comment]
Any examples? I've switched from swagger-js as its bundle size was ridiculous and have now generated the api.ts file from the codegen editor. It's a Create React App. How should the client be used? More specifically, how do you create the configuration (with a jwt token for each request) and use the generated stub functions? Thanks.

I can see a configuration.ts. I need to be able to use this generated client once the user has successfully logged in via AWS Cognito. Is there an example anywhere?

**Comment by BeryJu** [comment]
For any other people that stumble upon this issue, this is how its working for me (no idea if it's 100% intended this way):

For configuration, I have a global object in a file, for example `./api/Config.ts`:

```typescript
export const DEFAULT_CONFIG = new Configuration({
    basePath: "/api/v2beta",
    // other config options
    headers: {
        "foo": "bar",
    },
    middleware: [
       // Some middleware,
    ],
});
```

Then for middleware, a base class can look like this (all imports should be resolvable from your IDE)

```typescript

export class APIMiddleware implements Middleware {

    pre(context: ResponseContext): Promise<FetchParams | void> {
        return Promise.resolve({ url: context.url, init: context.init });
    }

    post(context: ResponseContext): Promise<Response | void> {
        return Promise.resolve(context.response);
    }
}
```

**Comment by wujibear** [comment]
I've been going through the generated code to try to understand what's expected, but I'm still having a heck of a time.
This is a helpful example as this is possibly the first time I saw that I could send the `basePath` through the configuration.

I'm having issues where I can make GET requests work ok locally or to prod, but no request body is sent when POSTing to my prod instance. Running locally, both services are on localhost on different ports and I can see a payload being sent in the request. That works.
As soon as I use my prod url, the exact same set up and call strips out the request payload so my call fails. Quite sure I have CORS set up for my prod API, and GET requests with no params work ok for it.

I may be better off to make my own issue for help on that, but the main issue is the same.
I don't know where to look for documentation on how to use the `typescript-fetch` SDKs so that it makes calls to my API correctly.
