### ISSUE TITLE
[BUG] [angular-typescript] Incorrect JSON object in HTTP request multipart form data

### ISSUE THREAD

**Issue by Beaurpi** [OpenAPITools/openapi-generator#2733]
Hi there,

I've figured out that there is an issue with the code generated, when using a multipart/form-data object.
Declare a POST method with the following requestBody:

```
'/test/upload':
post:
requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                title:
                  type: object
                  properties:
                    en:
                      type: string
                    fr:
                      type: string
                fileName:
                  type: string
                  format: binary
```

It's related to the generated code in angular typescript.
in the generation command line i'm using the following:
`-g typescript-angular`

the generated service will have a good signature:
`public uploadFile(id: string, name?: string, title?: UploadTitle, .....`

But the HTTP post, will not pass a JSON for the parameter 'TITLE'.
It will actually encode the object as string.
As a result the 'title' parameter will be

```
-----------------------------8302951520691
Content-Disposition: form-data; name="title"

[object: Object]
```
Instead the parameter title should be
```
-----------------------------8302951520691
Content-Disposition: form-data; name="title"

{ en: 'sometext', fr: 'loren ipsum' }
```

**Comment by macjohnny** [comment]
The problem is due to the following lines of code:
https://github.com/OpenAPITools/openapi-generator/blob/044961f481bcfd121f4f46b6914ed970317acf10/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L309

https://github.com/OpenAPITools/openapi-generator/blob/044961f481bcfd121f4f46b6914ed970317acf10/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L287

@Beaurpi would you like to give it a try and implement a fix?

**Comment by Beaurpi** [comment]
@macjohnny That would be a pleasure. I would be totally newbie in .moustache things and this project.
So I think it would be better that someone else is taking care of this. I am missing a bit of time to get deep inside the project though...
