### ISSUE TITLE
[BUG] Tests are failing on the master branch after a recursive clone

### ISSUE THREAD

**Issue by SeanFarrow** [OpenAPITools/openapi-generator#2815]
@wing328 
Bug installing the generator after a recursive clone

##### Description
after cloning the repository with a recursive clone using the command:
git clone --recursive https://github.com/OpenApiTools/OpenApi-Generator.git

and then attempting to install the master branch using 

mvn install

5 tests fail as follows:

org.openapitools.codegen.java.jaxrs.JavaJAXRSCXFExtServerCodegenTest#generateJsonAnnotationForPolymorphism
Exception
java.lang.AssertionError: expected [true] but found [false]
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.checkFileContains(JavaJaxrsBaseTest.java:59)
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.generateJsonAnnotationForPolymorphism(JavaJaxrsBaseTest.java:52)

org.openapitools.codegen.java.jaxrs.JavaJAXRSSpecServerCodegenTest#generateJsonAnnotationForPolymorphism
Exception
java.lang.AssertionError: expected [true] but found [false]
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.checkFileContains(JavaJaxrsBaseTest.java:59)
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.generateJsonAnnotationForPolymorphism(JavaJaxrsBaseTest.java:52)

org.openapitools.codegen.java.jaxrs.JavaJaxrsResteasyServerCodegenModelTest#generateJsonAnnotationForPolymorphism
Exception
java.lang.AssertionError: expected [true] but found [false]
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.checkFileContains(JavaJaxrsBaseTest.java:59)
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.generateJsonAnnotationForPolymorphism(JavaJaxrsBaseTest.java:52)

org.openapitools.codegen.java.jaxrs.JavaJerseyServerCodegenTest#generateJsonAnnotationForPolymorphism
Exception
java.lang.AssertionError: expected [true] but found [false]
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.checkFileContains(JavaJaxrsBaseTest.java:59)
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.generateJsonAnnotationForPolymorphism(JavaJaxrsBaseTest.java:52)

org.openapitools.codegen.java.jaxrs.JavaResteasyEapServerCodegenModelTest#generateJsonAnnotationForPolymorphism
Exception
java.lang.AssertionError: expected [true] but found [false]
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.checkFileContains(JavaJaxrsBaseTest.java:59)
	at org.openapitools.codegen.java.jaxrs.JavaJaxrsBaseTest.generateJsonAnnotationForPolymorphism(JavaJaxrsBaseTest.java:52)

I'm trying to install the generator so that I can contribute to various C# issues.

Either I am missing something when cloning/installing the project, or there appears to be an error in one or more of the tests shown above.
I'm cloning on windows and have tried with/without admin privelliges.

**Comment by wing328** [comment]
It works for me on my Windows box with JDK8. What java version are you using?

It's also building fine in our CI (Appveyor): https://github.com/OpenAPITools/openapi-generator/blob/master/appveyor.yml#L52

**Comment by SeanFarrow** [comment]
I’m using jdk 12.0.1.
If I can get hold of a jdk 8 release, I’m happy to install that instead.

**Comment by wing328** [comment]
Have you tried downloading the installer via https://github.com/ojdkbuild/ojdkbuild#downloads-for-windows-x86_64 ?

**Comment by SeanFarrow** [comment]
Which of these is the best to download for maximum support?

**Comment by wing328** [comment]
I've no idea as I seldom work on a Windows machine.

**Comment by wing328** [comment]
If you've Docker installed, then you can still compile openapi-generator locally without installing Java, Maven.

**Comment by SeanFarrow** [comment]
Ok, what do I need to do to compile with docker and get artifacts out of the build?

**Comment by thiakil** [comment]
This appears to be a line endings issue; a quick & dirty fix is on `org/openapitools/codegen/java/jaxrs/JavaJaxrsBaseTest.java:56` to add `.replaceAll("\\r\\n", "\n")`

**Comment by SeanFarrow** [comment]
Ok, is there a java primitive we can use?
If the below fix is added as is, I suspect tests will fail on CI/in Docker.

**Comment by thiakil** [comment]
Well if the CI passes without, it already has the correct line endings and the fix would do nothing.

The proper fix would probably be to prevent a mismatch to begin with - either in the `.gitattributes` for the template files, or using a template file for the expected output data so that they get given the same line endings by git

**Comment by wing328** [comment]
@SeanFarrow please go to https://adoptopenjdk.net/ and download the installer to install JDK8 in your windows machine (which works for me in my Windows laptop). Let me know if you need any help.

**Comment by drl-max** [comment]
@SeanFarrow, I've been having the same issue trying to build the project on Windows for a while now. Took a look this morning and think I figured out a viable solution. Feel free to try out my PR #2919 and see if it works for you too.

I find it odd that @wing328 wasn't experiencing this issue on his Windows machine, unless his OS has been changed to use \n as it's EOL character.

**Comment by SeanFarrow** [comment]
Thanks, I’ll take a look over the weekend. In brief though, what does your PR do?

**Comment by drl-max** [comment]
As @thiakil pointed out, it's an issue with the line endings in the test.  It's my guess that the JaxRS generator is creating a file that uses the OS line ending (\r\n). The test then opens that file and attempts to compare each line against an expected value... but that value just has \n for a line ending, so it fails.

All that being said, my PR is failing it's run through AppVeyor, so I'm likely going to have to continue playing with this to find something that works.

**Comment by drl-max** [comment]
After doing a bit more digging today, I'm gonna go ahead and kill my PR. While it fixed the problem locally (looking for \n instead of the native \r\n), it obviously didn't fix the problem for good.

For what it's worth, I found that I could successfully run `mvn clean test` on the master branch after running `dos2unix` on all of the Mustache templates for JavaJaxRs.

1. Change directory to `openapi-generator\modules\openapi-generator\src\main\resources\JavaJaxRS`
2. Execute Powershell script `PS > dir *.mustache -Recurse | Resolve-Path -Relative | ForEach-Object -Process { dos2unix $_ }`
3. Execute `mvn clean test`
4. Rejoice

Personally, I think this means that the environment AppVeyor uses might have a different configuration for Git than the typical Windows setup. That would explain why the expectation of finding a \n instead of \r\n works for the test. Ideally, my original solution should've worked since the EOL character would've been determined by the environment and not by the configuration of Git.

**Comment by thiakil** [comment]
Largely it's related to the [core.autocrlf](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code) setting.

A `.gitattributes` file could also help mitigate the issue by forcing a particular line ending for a particular file pattern. But ideally, the test shouldn't *require* any particular line ending (or otherwise preemptively normalise them)

**Comment by drl-max** [comment]
I've made another attempt at a PR to fix this. My approach this time around was to remove all formatting from both strings before attempting to test them.  This entails removing all newlines (Windows and Unix style) and replace instances of multiple whitespace characters with only one.  This way, it doesn't matter what kind of whacky newline-handling nightmare the environment might be in, the tests should still pass.

I'm currently waiting for the PR to validate through the CI. 🤞

**Comment by wing328** [comment]
> I find it odd that @wing328<https://github.com/wing328> wasn't experiencing this issue on his Windows machine, unless his OS has been changed to use \n as it's EOL character.

@drl-max I didn't do anything special. Git is the default setup.

I'm sorry to hear you've been experiencing issue building the project locally in your machine.

Looking forward to your PR 👍

**Comment by wing328** [comment]
Closed via #2927. Thanks for the PR by @drl-max 

@SeanFarrow let us know if you still need any help on this.
