### ISSUE TITLE
[REQ] Generate python client with using pydantic models

### ISSUE THREAD

**Issue by timothyjlaurent** [OpenAPITools/openapi-generator#3269]
##### Description

Pydantic offers a clean model api with fast validation. It would be a nice enhancement to generate such models from openapi specs.

**Comment by spacether** [comment]
pydantic coerces data types into the defined types
openapi constrains payloads to a set of allowed types and sometimes defines validations that must be done and other schemas (oneaOf/anyOf/allOf discriminated schemas that must also be validated against)

In my opinion coercion goes agains the type constraints that openapi defines because it is changing the type of the payload that you are making assertions against.

That being said, I understand the motivation. The python-fastapi server generator uses pydantic:
https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-fastapi.md#metadata

Our [python-experimental](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-experimental.md#metadata) generator does NOT do coercion on received payloads and it has
- robust run time type + validation checking
- oneOf/anyOf/allOf support including imposing type constraints in composed schemas
- type hints for models, properties, endpoint parameters, and responses

I encourage you to give it a look and see if it will meet your needs.

**Comment by spacether** [comment]
Update: the [python-fastapi](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-fastapi.md) generator was created which is a server generator and it uses pydantic for model generation
So it's not a client but it uses pydantic

**Comment by spacether** [comment]
Why did you close it? There's no pydantic client yet.

**Comment by timothyjlaurent** [comment]
It's such an old issue -- I get feedback once every year or 2 - I've moved on. Feel free to reopen it.

**Comment by spacether** [comment]
No worries, I was just curious and don't want to reopen if
