### ISSUE TITLE
[BUG] Typescript-fetch generator not respecting the specification

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-generator#3349]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

There was a big refactoring in the typescript-fetch generator that was introduced with version 4.X.X.  A lot of stuff has been added and it's good work. Unfortunately, there is one big problem. The new generated code is not following the specification which break every software using the previous fetch generator. 

Let me explain with an example:

If you look at the test (which currently passes), you can see that the `addPet` function doesn't receive a `Pet` object as expected. 
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/typescript-fetch/tests/default/test/PetApi.ts#L19

Instead, it uses an interface called `AddPetRequest` which doesn't exist at all in the spec.
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/typescript-fetch/builds/default/apis/PetApi.ts#L25

You can see in the spec here that it should receive a simple `Pet` object.
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml#L36

##### openapi-generator version

Latest 4.0.3 and master

##### OpenAPI declaration file content or url

Using default `petstore.yaml` used for the samples.

##### Command line used for generation

`./bin/typescript-fetch-petstore-all.sh`

##### Steps to reproduce

Just generate the code using the `sh` script.

##### Related issues/PRs

N/A

##### Suggest a fix

We need to remove the `Request` interface. The code should respect the spec.

For example, the test should be like this:

```
it('should add and delete Pet', () => {
      return api.addPet(fixture).then(() => {
    });
});
```

instead of this:

```
it('should add and delete Pet', () => {
       return api.addPet({ body: fixture }).then(() => {
   });
});
```

**Comment by JFCote** [comment]
I will see if I can create a PR for this.

**Comment by TiFu** [comment]
I disagree that it breaks the spec - I believe the spec only defines how the HTTP request for `addPet` has to look like, not *how* the parameters are passed around in the code generator. 

With that out of the way, I think both options - `AddPetRequest` interface and the `addPet(pet: Pet)` - have their merits. In particular, `AddPetRequest` is very useful if you have an endpoint with a lot of parameters and makes the code using the ts-fetch client easier to read, while `addPet` is closer to what you would expect from the spec.

I would propose to either add a switch to the generator with which users can decide to use either of the two options (I think one of the other generators uses this) OR to simply implement both options in the client, instead of removing the changes again.

**Comment by JFCote** [comment]
@TiFu Fair point.

I will update my PR and see which of the 2 options is easier to implement and don't mess the mustache too much. I'll let you know when it's ready.

**Comment by macjohnny** [comment]
related issue: https://github.com/OpenAPITools/openapi-generator/issues/865
