### ISSUE TITLE
[BUG] bad import for SpringBoot model

### ISSUE THREAD

**Issue by bademux** [OpenAPITools/openapi-generator#3461]
The commit https://github.com/OpenAPITools/openapi-generator/commit/0fca90133ce097f987098e6121936c0ffcb210a8 adds 
`` `import org.openapitools.jackson.nullable.JsonNullable; ```

Why I need to import the class if I don't need it?

**Comment by macjohnny** [comment]
cc @cbornet

**Comment by vmisra2018** [comment]
I also saw this. It is unused import and it forces to add dependency.

**Comment by Fjolnir-Dvorak** [comment]
I think this issue is far bigger. In a lot of generators there are a heck of a ton unused imports in every file. My IDE really hates me for that since there are generated files which are not annotated as generated in the comments. I think the best option would be to make each single import conditional which would bloat the whole generator in its current state.

Each import would be associated with one or multiple features. If one or more of those features are used the import should be set as well as other conditional events like adding the dependency to the dependency management system.
That feature could be implemented as a base feature for all languages and after that could be adopted to each individual generator.

**Comment by RupprechJo** [comment]
The problem is even bigger, if you want to use the generator in build tool, after generating it does not compil witout removing that unused import, so you cannot use it in an automated build!

**Comment by jmini** [comment]
I have started to add [google-java-format](https://github.com/google/google-java-format) as post-generation step when I use OpenAPI-Generator.

It removes the unused imports and format the code.
There are gradle and maven plugins available.

**Comment by Fjolnir-Dvorak** [comment]
@jmini That is a good solution to start with. But that only fixes the issue for Java. Since the generator is not java specific I tend to not like that as a final solution.

**Comment by bademux** [comment]
@jmini sound like a big hack. This kind of solution tends to hide problems. Why to not fix the bug as it perfectly visible and reproducible.

**Comment by jmini** [comment]
@bademux: feel free to propose a PR.

The problem is that the way the generator is built, the imports are written first and at this point in time the information to know if one of the field will use `JsonNullable` in the class content or not is not present.

**Comment by bademux** [comment]
@jmini Well, it a bit of a work to propose new generator :)
Anyway, thanks for discussion!

Closed as a "Won't fix" (until global generator context with all needed information will be passed)

**Comment by jmini** [comment]
According to https://github.com/OpenAPITools/openapi-generator/pull/3474#issuecomment-520393508, I think that @bkabrda added the code you wanted:

> It also makes sure that the imports for JsonNullable are only added when at least one of the model's fields actually uses that.

Can you test with the latest SNAPSHOT?
