### ISSUE TITLE
[typescript-rxjs] How to handle server errors?

### ISSUE THREAD

**Issue by kino90** [OpenAPITools/openapi-generator#3511]
Hello, 
Thanks a lot for all the efforts in making this!

I'm using typescript-rxjs, but I'm having troubles handling server errors responses.

##### Description

I am trying to use a `Post` Middleware to react to ajax errors (status >= 300) in a centralized pattern. 
This post-middleware should only look at the response object and conditionally trigger actions on my Redux store or trigger a redirect (e.g for the 401 unauthorized error).

The problem is that if `res.status`  is >= 300 the generator will `throw res`, so the Post Middlewares are **not executed at all**. 

So.. is there a way I can handle my errors globally with the typescript-rxjs generator?

##### openapi-generator version
0.0.16-4.03

##### Steps to reproduce

Return 401 or 500 from server

##### Suggest a fix/enhancement

Run Middlewares also on error?
If I remember correctly the axios generator will run post middlewares also on errors.

**Comment by macjohnny** [comment]
cc @denyo

**Comment by denyo** [comment]
Not sure if a middleware is the right place. I personally never used the `post` ones but I could only imagine it for post request transformations or logging.

What I personally do is, I use `redux` with `redux-observable` for async calls. There you have `epic`s that call a service method which then calls the generated api call. The service method does some mapping but you could also call the generated controllers directly. 

Since it's all observables you can then `pipe` some operators into the stream. The one that you're looking for is `catchError`. There you can do the error handling. 

It isn't global handling since it occurs in every `epic` but then global handling probably isn't something you want since there always are exceptions, e.g. an expired token causing a 401. There you want to force a logout but that kind of handling doesn't work for a failed login call.

The same `catchError` could also be applied in a regular `subscribe` chain like `someCall().pipe(map(...), catchError(err => ...)).subscribe(data => ...)`.

**Comment by kino90** [comment]
Thanks for the reply @denyo! 
We were trying using post middlewares to avoid adding another dependency (which, *by the way*, is already in the '*things to add*' list)! 
We'll probably add `redux-observable` to our app, then 👍

**Comment by evanjmg** [comment]
@kino90  this is still an issue, using redux observable for middleware isn't a smart widely acceptable solution. post middle ware should always fire no matter what

**Comment by stefanpl** [comment]
@macjohnny @evanjmg @denyo  has anyone actually taken a look at this issue?

We're using the `typescript-rxjs` generator (with `@openapitools/openapi-generator-cli@2.20.2`), and getting the same behavior: **post middleware is not executed in case of an error**.

Any chance of seeing this fixed?

**Comment by stefanpl** [comment]
Using this in `runtime.ts` fixes the issue

```
 private rxjsRequest = <T>(params: AjaxConfig): Observable<AjaxResponse<T>> =>
        of(params).pipe(
            map((request) => {
                this.middleware.filter((item) => item.pre).forEach((mw) => (request = mw.pre!(request)));
                return request;
            }),
            concatMap((args) =>
                ajax<T>(args).pipe(
                    map((response) => {
                        this.middleware.filter((item) => item.post).forEach((mw) => (response = mw.post!(response)));
                        return response;
                    }),
                    catchError((error) => {
                        // Transform HTTP errors into successful responses
                        // This prevents rxjs/ajax from throwing on status > 300
                        if (error.response !== undefined) {
                            let errorResponse = {
                              status: error.status,
                              response: error.response,
                              responseType: error.responseType,
                              originalEvent: error.originalEvent,
                              xhr: error.xhr,
                              request: error.request,
                            } as AjaxResponse<T>;

                            // Apply post middleware to error responses too
                            this.middleware.filter((item) => item.post).forEach((mw) => (errorResponse = mw.post!(errorResponse)));

                            return of(errorResponse);
                        }
                        // Re-throw non-HTTP errors (network errors, etc.)
                        throw error;
                    })
                )
            )
        );
```

**Comment by macjohnny** [comment]
@stefanpl do you want to send a PR to fix this?
