### ISSUE TITLE
[BUG] enum issue when using generated dart 

### ISSUE THREAD

**Issue by boojongmin** [OpenAPITools/openapi-generator#4157]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
I meet a bug when using a generated dart source.

<img width="449" alt="22" src="https://user-images.githubusercontent.com/9567723/66804149-a83b5080-ef5c-11e9-8425-d4dbd1ffc94a.png">

because json serializer can't serialize enum type directly.
so I modify code like below image.(add '.value')

<img width="222" alt="a" src="https://user-images.githubusercontent.com/9567723/66804248-ea649200-ef5c-11e9-8f13-6850da3eefde.png">

would you fix this bug?

##### openapi-generator version

4.1.3

**Comment by wing328** [comment]
> so I modify code like below image.(add '.value')

@boojongmin can you please file a PR with the suggested fix?

`dart2` templates can be found in https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/dart2

**Comment by b1rdG** [comment]
Hi,

On the version `4.3.1` the [serialize function](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart2/api_client.mustache#L105) delegate on dart convert library `json.encode()`. It return an error because serializing this enums because the enum is not "encodable" (is not a number, boolean, string, null, list or a map), so the `encode()` method looks for a `toJson()` on the Object passed:

```dart
  /// If [toEncodable] is omitted, it defaults to a function that returns the
  /// result of calling `.toJson()` on the unencodable object.
```

And, the enum objects doesn't have this method...

**Comment by b1rdG** [comment]
Hi I created a PR https://github.com/OpenAPITools/openapi-generator/pull/6111

**Comment by agilob** [comment]
This should be closed @b1rdG @wing328
