### ISSUE TITLE
[BUG] Kotlin escaped reserved words have HTML entities not backticks

### ISSUE THREAD

**Issue by dalewking** [OpenAPITools/openapi-generator#4537]
##### Description

Note that this is difficult to express without markdown translating what I enter.

Kotlin supports  escaping reserved words by surrounding it with backticks as in &#x60;data&#x60;

I have an API that has a parameter named data that is a reserved word in Kotlin and the generator is recognizing that it is reserved, but when the source file is written the backticks are being turned into HTML character entities.

So instead of seeing &#x60;data&#x60; in the code what I see is `&#x60;data&#x60;`

##### openapi-generator version

4.2.1

##### OpenAPI declaration file content or url

Here is the URL of the API I am trying to work with: https://api.youneedabudget.com/papi/spec-v1-swagger.json

##### Command line used for generation

Gradle.kts declaration I am using:

    val swaggerInput = file("ynab-v1-swagger.json")
    val swaggerOutputDir = file("build/swagger")

    openApiGenerate {
        inputSpec.set(swaggerInput.toString())
        outputDir.set(swaggerOutputDir.toString())
        generatorName.set("kotlin")
        invokerPackage.set("mypackage.ynab.client")
        modelPackage.set("mypackage.ynab.client.model")
        apiPackage.set("mypackage.client.api")
        configOptions.put("dateLibrary", "java8")
    }

##### Steps to reproduce

Generate kotlin code of an API that uses a reserved word

**Comment by dalewking** [comment]
Looks like the solution in my case is to replace all instances of {{paramName}} with {{{paramName}}} in kotlin-client/api.mustache, but that only fixes it for parameter names. Probably needed many other places as well.

**Comment by dalewking** [comment]
From what I read {{&paramName}} is another alternative. For now I have created a gradle step that copies and renames those parameters since they are in endpoints that I am not even using.

**Comment by stapel** [comment]
Pretty much nothing in kotlin, except maybe comments and KDocs, should be html-encoded, the codegen handles that.

**Comment by fleskesvor** [comment]
I'm experiencing the same issue with generated Kotlin with version 4.2.2 of the Gradle plugin.

**Comment by jimschubert** [comment]
For those experiencing this in older versions of the generator, you can modify the template and change `{{paramName}}` to `{{{paramName}}}` to resolve without upgrade. To change the template, you'd copy the affected template file to some directory retaining the directory structure after `kotlin-client`.

For example, if you wanted to modify `modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/api.mustache`, you would create some directory (e.g. `~/my_templates`) and add the file at `libraries/multiplatform/api.mustache` under that directory (final: `~/my_templates/libraries/multiplatform/api.mustache`). Make the adjustment listed above, and generate with the `-t` option pointing to the base directory (example: `-t ~/my_templates`).

Full details on customizing the template are at https://openapi-generator.tech/docs/templating.

I'll have this fixed in #5221 and will include the additional fix from @stapel in that PR.
