### ISSUE TITLE
[Gradle Plugin]: openApiValidate - how to validate multiple yaml files ?

### ISSUE THREAD

**Issue by rolandg333** [OpenAPITools/openapi-generator#4643]
##### Description

i can validate a single .yaml file using 

openApiValidate {
    inputSpec = 'file.yaml'
}

But my project has several .yaml files.
I would like to validate them all before packing them up into a .zip artifact on a build step.

How ?

##### openapi-generator version
id 'org.openapi.generator' version '4.2.1'

**Comment by jimschubert** [comment]
Hey. Sorry, just getting caught up on a huge backlog of issues/questions that we accrued over the holidays.

You've probably already figured this one out, but I wanted to comment for anyone else who might find your question.

```
task validateGoodSpec(type: org.openapitools.generator.gradle.plugin.tasks.ValidateTask){
    inputSpec = "$rootDir/petstore-v3.0.yaml".toString()
}

task validateBadSpec(type: org.openapitools.generator.gradle.plugin.tasks.ValidateTask){
    inputSpec = "$rootDir/petstore-v3.0-invalid.yaml".toString()
}

task validateSpecs(dependsOn: ['validateGoodSpec', 'validateBadSpec'])
```

The openApiValidate definition you've shown in your description is a project extension which has an identical task. All tasks in the plugin can be defined explicitly as I've done above. There are multiple examples in the [local-spec](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle) sample.

If there's interest, we can add the example to our readme or sample script. I'm hesitant to do this because we already have examples of customizing `GenerateTask`, and I think it'll add value and possible make the readme harder to follow if each project extension includes an example of how to extend the underlying task. In that regard, I hope you don't mind that I'll close the issue?

**Comment by jimschubert** [comment]
I decided to add docs in #5167. I figured if you had the question, others probably do as well.
