### ISSUE TITLE
[BUG][SCALA] instantiationType array is missed in Scalatra generator

### ISSUE THREAD

**Issue by chameleon82** [OpenAPITools/openapi-generator#5507]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

Scalatra server template generating wrong default value `new null[]()` instead of 'List[String].empty` due missed `array` instantiationType

##### openapi-generator version

`2.3.0-SNAPSHOT`

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

##### Steps to reproduce

regenerate scalatra server - default value has incorrect value `new null[]()`. should be `List[String].empty`

##### Related issues/PRs

Related code https://github.com/OpenAPITools/openapi-generator/commit/25036e48d5ae47ce44c0116e6c131ad5bffd0b24#diff-62e3a15550247bb6a76bdc7745faa850R265

##### Suggest a fix

Add `instantiationTypes.put("array", "List");` at abstract level or per template if array has specific meaning

@jimschubert

**Comment by jimschubert** [comment]
Hm. This existed when I stepped through the code last. I wonder if I forgot to commit or if it came from DefaultCodegen and has since been removed. Or maybe it was only defined in a derived generator.

I imagine we'd have the same issue for all OpenAPI types which should not be Java types and really shouldn't rely on DefaultCodegen to "do the right thing" (like `map` should instantiate with immutable `Map` by default).
