### ISSUE TITLE
Model not generated with the right type (allOf)

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-generator#582]
##### Description

A member of a model is not using the model type requested by the spec. Please check the example for a better explanation

##### openapi-generator version

Master (3.1.1-SNAPSHOT)

##### OpenAPI declaration file content or url

This is a self contained file that reproduce the issue

```yaml
swagger: "2.0"
info:
  description: "dfsdfsdfs"
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "https"
- "http"
paths:
  /lifecycles:
    put:
      tags:
        - Device
      summary: xxxxxxx
      operationId: editDeviceLifecycles
      parameters:
      - in: body
        name: device-lifecycle-update-info
        required: true
        schema:
          $ref: "#/definitions/DeviceLifecycleCore"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/DeviceLifecycleCore"
definitions:
  DeviceLifecycleCore:
    type: object
    description: "DeviceLifecycleCore"
    properties:
      aaa:
        type: string
        description: "aaa"
      bbb:
        type: string
        description: "bbb"
      ccc:
        type: string
        description: "ccc"
      returnSoftwareStatus:
        $ref: "#/definitions/DeviceLifecycleStatus"
  DeviceLifecycleStatus:
    type: object
    description: "DeviceLifecycleStatus"
    allOf:
      - $ref: "#/definitions/DeviceLifecycleStatusCore"
      - type: object
        required:
          - id
        properties:
          id:
            type: integer
            format: int64
            description: "Id associated with the status"
            example: 123
  DeviceLifecycleStatusCore:
    type: object
    description: "DeviceLifecycleStatusCore"
    properties:
      name:
        type: string
        description: "Name"
      details:
        type: string
        description: "Any additional information needed for the status"
        example: "Something is wrong"
```

As you can see `returnSoftwareStatus` is supposed to be of type `DeviceLifecycleStatus`. If you look in the generated code, you will see that it is of type `DeviceLifecycleStatusCore` instead:

```java
public DeviceLifecycleCore returnSoftwareStatus(DeviceLifecycleStatusCore returnSoftwareStatus) {
    this.returnSoftwareStatus = returnSoftwareStatus;
    return this;
  }

   /**
   * DeviceLifecycleStatus
   * @return returnSoftwareStatus
  **/
  @Valid
  public DeviceLifecycleStatusCore getReturnSoftwareStatus() {
    return returnSoftwareStatus;
  }

  public void setReturnSoftwareStatus(DeviceLifecycleStatusCore returnSoftwareStatus) {
    this.returnSoftwareStatus = returnSoftwareStatus;
  }
```

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -i ./swagger.yaml --generator-name java-play-framework -o generatedServer -DhideGenerationTimestamp=true,booleanGetterPrefix=is`

##### Steps to reproduce

Just run the command above

##### Related issues/PRs

None

##### Suggest a fix/enhancement

?

**Comment by macjohnny** [comment]
@JFCote I had a similar issue with `3.0.0`, which was solved by upgrading to `3.1.0`. In my case it was the body parameter that had the wrong type.

**Comment by JFCote** [comment]
@macjohnny Yeah I had this too. It's all fixed with 3.1.X but this is something else. I'm using 3.1.1-SNAPSHOT and still got this. I think it's a different use case.

**Comment by jmini** [comment]
Related issues/PRs: https://github.com/OpenAPITools/openapi-generator/issues/340 (but not directly)

**Comment by rubms** [comment]
I am also affected by this bug.

The problem comes from the https://github.com/OpenAPITools/openapi-generator/commit/a897feef50989d8b0d0238c067eebaef4f7f6c70 commit in the https://github.com/OpenAPITools/openapi-generator/pull/360 pull request. More precisely, from this change https://github.com/OpenAPITools/openapi-generator/commit/a897feef50989d8b0d0238c067eebaef4f7f6c70#diff-7cb46fa53f89a458a7b7cb201d2214a8R1527.

Before this commit, when this properties where not un-aliased, a `Schema` instance was used to compose the model property of composed models (models containing `allOf`). This `Schema` instance contained the appropriate $ref field indicating the original datatype name, from which the data type name was correctly extracted via `DefaultCodeGen::getSchemaType()`. 

Now, with this un-aliasing, instead of a `Schema` with the proper $ref field, a `ComposedSchema` is used to compose the model properties of composed datatypes. In those ComposedSchemas the original data type name is lost and `DefaultCodeGen::getSchemaType()` returns the datatype of the first of the models involved in the `allOff` clause:

```java
    public String getSchemaType(Schema schema) {
        if (schema instanceof ComposedSchema) {
            ComposedSchema cs = (ComposedSchema)schema;
            if (cs.getAllOf() != null) {
                Iterator var3 = cs.getAllOf().iterator();

                while(var3.hasNext()) {
                    Schema s = (Schema)var3.next();
                    if (s != null) {
                        schema = s;
                        break;
                    }
                }
            }
        }
...
```

Though the https://github.com/OpenAPITools/openapi-generator/pull/360 pull request fixed the issues #255 and #191, it originated this #582 issue.

**Comment by jmini** [comment]
This change looks good to me! Please create a PR for it.
In the ideal case, a unit test could help to ensure no regression.

**Comment by rubms** [comment]
Just created the https://github.com/OpenAPITools/openapi-generator/pull/704 pull request in order to get this issue fixed.

**Comment by JFCote** [comment]
Fixed by https://github.com/OpenAPITools/openapi-generator/pull/704
