### ISSUE TITLE
[Announcement] Deprecation of JDK7 support

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#6158]
Given that JDK7 has already reached the EOL, we'll remove JDK7 support so only JDK8 or later will be supported by all the Java (client/server) generators in the upcoming v5.0.0 major release.

The auto-generated Java code may or may not work with JDK7 and one workaround is to stick with v4.x for the time being or customize the templates to make it work with JDK7.

**Comment by hleb-albau** [comment]
According to https://www.jetbrains.com/lp/devecosystem-2019/java/ java7 is used by 13% of Java developers at current time. Is it good choose right now?

**Comment by wing328** [comment]
> Is it good choose right now?

Depending on how you define "good". Ideally we want to support JDK7 (or even JDK6) if it's still "popular" among the Java developer community but unfortunately, JDK7 has reached the EOL and we would rather prioritize our resources on JDK8+ instead.

Users using JDK7 can still use OpenAPI Generator 4.x. With customized templates, they can do whatever they want and keep maintaining the customizations. Of course, it's not recommended to use JDK which has reached EOL so definitely better to upgrade to a newer (supported) version of JDK if possible.

Is there a particular use case that must use JDK7? Please kindly share more.

**Comment by agilob** [comment]
>java7 is used by 13% of Java developers at current time

because all the fin-tech and medical companies are not moving away as they consider java8 move it too big to make. Keep in mind that openapi-generator is mostly used for new projects, but "java7 is used by 13%" means maintenance of projects created in 2005. I can't imagine anyone starting a new project in java7 now - lack of support from distributions, no security patches, no TLS support - your internet connection will break once responsible and security compliant companies move away from SSL to TLS1.3 (since 1 - 1.1 are also deprecated), no native containerization support... you know, all the things have changed in java since 20**11**.

IMO openapi should start discussion about dropping java8, or making java11 (_var_) the default option, this would simplify development and maintenance of templates.

**Comment by hleb-albau** [comment]
You are right, it's no sense to create new project based on java7. But this related to server side of openapi. But if you create b2b application, and most of your customers are enterprise companies, you have to support older versions of java. 

I am not a big fan of legacy, and dropping java7 seems okey for current moment(android studio has mature de-sugaring, we still have 4.x.x branch and etc). But dropping java8 seems big overkill. Although Java 10 and 11 have become more popular, Java 8 is still the most used version. Given that oracle extends java8 support til 2030, it seems java8 will be popular 5+ years.

**Comment by itaru2622** [comment]
I would like to prepare deprecation of java7 before it is gone.
Please let us know the estimated schedule or roadmap when java8 mode is ready to use for the investigation of the imact against our legacy implementation codes, before official release.
for example, in jaxrs-jersey, mustache files seem to be ready for java8, but it still generates java7 code in default at this moment.

**Comment by wing328** [comment]
Closing this as v5.0.0 has been released.
