### ISSUE TITLE
[Announcement][php-silex] Silex package is abandoned

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#6203]
[Silex](https://packagist.org/packages/silex/silex) package has been abandoned:
> This package is **abandoned** and no longer maintained. The author suggests using the [symfony/flex](https://packagist.org/packages/symfony/flex) package instead.

> **WARNING**: Silex is in maintenance mode only. Ends of life is set to June 2018. Read more on [Symfony's blog](https://symfony.com/blog/the-end-of-silex).

Should we mark `php-silex` generator as deprecated? Or we need to migrate to `symfony/flex` package instead?

**Comment by wing328** [comment]
Thanks for the update.

Yes we already have a php-symfony generator. Do we need one for `symfony/flex`?

Is the php-symfony generator actually using `symfony/flex` underneath?

**Comment by ybelenko** [comment]
I think this page explains it: [Upgrading Existing Applications to Symfony Flex](https://symfony.com/doc/current/setup/flex.html)

> Using Symfony Flex is optional, even in Symfony 4, where Flex is used by default. However, Flex is so convenient and improves your productivity so much that it's strongly recommended to upgrade your existing applications to it.

> Symfony Flex recommends that applications use the following directory structure, which is the same used by default in Symfony 4...

Another observation is `symfony/flex` [package type](https://getcomposer.org/doc/04-schema.md#type) is `composer-plugin` while `symfony/framework-bundle` is `symfony-bundle`(custom type).
> Is the php-symfony generator actually using `symfony/flex` underneath?

I think so. But let's wait for feedback from PHP committee, maybe they can say something.

cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @renepardon

**Comment by dkarlovi** [comment]
symfony/flex doesn't really replace Silex, it's a bit more complicated.

Silex was abandoned since Symfony bridged the gap between micro-framework and a full framework by making the base Symfony framework experience micro (or close to it). This means you get a tiny framework footprint from the start for any Symfony app you create. To not lose productivity getting that tiny app back to a "full framework state", they've introduced Flex which is basically automation around installing and managing dependencies (which is why it's a Composer plugin).

It allows you to go from the newly tiny Symfony app back to the "full framework" app with a command or two, doing most of the work required for you (adding / modifying config files, creating placeholder files / folders where needed, etc).

From my POV, there's not really a way or point to migrate Silex to Flex, they're not the same thing. If Silex itself is abandoned (which it is), the Silex generator should be too. Improving the Symfony package is a separate issue entirely.

**Comment by wing328** [comment]
@dkarlovi thanks for the details.

@ybelenko I'm ok renaming `php-silex` to `php-silex-deprecated` and mark the generator as deprecated.
