### ISSUE TITLE
[REQ] Feature Request - speed up + simplify sample generation

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#6333]
### Is your feature request related to a problem? Please describe.

- Local sample generation with `./bin/utils/ensure-up-to-date` without batch invocation takes a while, ~15 minutes.
- When users update [.sh](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/ada-petstore.sh) and [.bat](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/windows/android-petstore.bat) files, sometimes they forget to update the [json config files](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/csharp-petstore-net-40.json)
- the .sh/.bat/.json config files offer three ways to do the same thing (provide generator inputs). If we use only one way, that will force our users to update the correct files

## Describe the solution you'd like

Desired changes:
- always use batch_mode=True [here](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/utils/ensure-up-to-date#L15)
- convert all the .sh and .bat files to store their inputs in json or yaml files like https://github.com/OpenAPITools/openapi-generator/blob/master/bin/csharp-petstore-net-40.json
- eliminate the generator specific .sh and .bat files
- perhaps allow passing in a single generator name into ensure-up-to-date to allow generation of individual generators, like the old .sh and .bat files

## Describe alternatives you've considered

N/A

## Additional context

This ticket was created from a discussion with @jimschubert on Slack

**Comment by jimschubert** [comment]
Thanks for raising this issue…

I think most of the work for this would just be migrating from `*.sh` and `*.bat` files to JSON or YAML configs. Many of our shell scripts already take JSON config inputs in the `bin` directory.

Two things we'll need to consider:

* A few scripts use custom logic such as `bin/java-petstore-feign.sh`
* There may be cases where we'd want to support the `*POST_PROCESS_FILE` environment variables, but I think those should be avoided in general if we're requiring the community to also regenerate these samples

If we move to config-based generation via the `batch` command we may see only trivial performance gains on CI where we may only have 1-2 CPUs, but the target here would be improving the process for all contributors.

Going this route, I wonder also if it might make sense to sync config scripts with generator names. For example, have structures such as:

```
bin/samples/scala-akka/*.json
bin/samples/csharp-netcore/*.json
```

This would make it much clearer to contributors which paths need to be updated. Then, the update script could accept a csv of specific generators if people are concerned about modifying untouched generators. For example:

Generate everything in batch:

```
./bin/utils/ensure-up-to-date 
```

Generate everything in batch but warn on deprecated parameter:

```
./bin/utils/ensure-up-to-date --batch
```

Generate only two generators' samples:

```
./bin/utils/ensure-up-to-date scala-akka,csharp-netcore
```

A net positive to this approach is that we'd be able to keep all generators updated rather than only a subset due to the long generation time.

**Comment by jimschubert** [comment]
@spacether I wonder if you'd be willing to evaluate #6334?

**Comment by jimschubert** [comment]
I think this is good to close now after #6509 has been merged. Feel free to reopen if we've missed anything.

Scrolling back through some Drone builds, it looks like before my change it was 35-45 minutes an after my change it's more around 24-29 minutes. The 10-15 minute improvement is pretty huge.

![image](https://user-images.githubusercontent.com/109659/84848088-82e96f80-b020-11ea-8043-8bf4526c4ca3.png)

The differences in bitrise are negligible because it runs only swift generation.

AppVeyor now appears to take 7-11 minutes whereas before it was taking 20-29 minutes (or thereabouts). This is a 13-18 minute improvement.

AppVeyor master builds from today:
![image](https://user-images.githubusercontent.com/109659/84848779-cabcc680-b021-11ea-81fe-af07a4cfba64.png)


AppVeyor master builds from ~11 days ago:
![image](https://user-images.githubusercontent.com/109659/84848679-a3fe9000-b021-11ea-8342-cba286bbc61f.png)

CircleCI is harder to evaluate because I believe it's single-core and only 1 or 2 CPUs, meaning it can't really invoke the generation in batches through parallel scheduling. It also has some wildly different times because it reports full duration as including the wait times. It also spends about a half of the runtime downloading and extracting the cache and later compressing and storing the cache (which is ~8 GB).

In the below images, the actual run time are the grayer times on each node.

After my change on CircleCI looks like 39-42 minutes.
![image](https://user-images.githubusercontent.com/109659/84849252-e70d3300-b022-11ea-9731-e36f03d25038.png)

Previous CircleCI appears to have been ~41-86 minutes.
![image](https://user-images.githubusercontent.com/109659/84849176-bfb66600-b022-11ea-9f83-d40aa9ea3e8a.png)
