### ISSUE TITLE
[REQ] typescript-axios useSingleRequestParameter should mark parameter optional if all properties are optional

### ISSUE THREAD

**Issue by benwiley4000** [OpenAPITools/openapi-generator#6440]
Follow-up to #6288.

### Is your feature request related to a problem? Please describe.

If the `useSingleRequestParameter` flag is passed to typescript axios, then an object is a required parameter of all request functions, even if all object properties are optional, so I end up with code like this:

`myApiCall({})`.

## Describe the solution you'd like

The generator should be able to check if any of the params are required. If not, we can specify the whole object parameter optional with `?`.

**Comment by macjohnny** [comment]
@benwiley4000 good suggestion, would you like to implement this?

**Comment by benwiley4000** [comment]
@macjohnny perhaps, if you can point me to where I would need to look in the code.

**Comment by macjohnny** [comment]
should be somewhere here:

https://github.com/OpenAPITools/openapi-generator/blob/bde0d77c8f3f9ae831690beecfb0c4e70f37e7b8/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L295-L319

the
https://github.com/OpenAPITools/openapi-generator/blob/bde0d77c8f3f9ae831690beecfb0c4e70f37e7b8/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L297
part should already prevent generation of an interface if no parameters are available, but somehow this doesn't work. 
maybe @codeserk can help, as he implemented this feature in https://github.com/OpenAPITools/openapi-generator/pull/6288

**Comment by codeserk** [comment]
@benbenw 
Hello!
That sounds indeed like a legit suggestion, `myApiCall({})` hurts a bit :D 
I'm not sure if this is going to be straight forward to implement tho, since maybe we need to change something in Java to determine whether all the parameters of the request are optional or not.

I think this is the right line to check in `mustache`:
https://github.com/OpenAPITools/openapi-generator/blob/bde0d77c8f3f9ae831690beecfb0c4e70f37e7b8/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L354

We should add `?` like this `requestParameters?:` in case that condition is set to true (all the request params are optional). We should probably add a guard, or default to `{}` in the first line of the method too.

I can take a look a bit later :)
