### ISSUE TITLE
[REQ][Slim4] Getter and setters for the models (or a not private visibility to properties)

### ISSUE THREAD

**Issue by TechPrivacyLab** [OpenAPITools/openapi-generator#6626]
### Is your feature request related to a problem? Please describe.

The php-slim4 generator generate models with private properties so they are not accessible from other classes nor extendable.
Every time a models is instantiated the object results in an empty object (with null properties).

## Describe the solution you'd like

The php-slim4 generator should generate models with either public properties or getters and setters (and maybe a constructor from associative arrays) like the php-symfony generator.

## Describe alternatives you've considered

Currently I don't use models at all... For the response I create associative arrays structured according to the OpenAPI config file.

## Additional context

A generated model from the sample directory:
https://github.com/OpenAPITools/openapi-generator/blob/3b9cb14025ac4ae90909ad5ba98f316ba5546986/samples/server/petstore/php-slim4/lib/Model/Pet.php
The same model generated with php-symfony:
https://github.com/OpenAPITools/openapi-generator/blob/3b9cb14025ac4ae90909ad5ba98f316ba5546986/samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Pet.php

I found a mustache file with the `private` directive.
https://github.com/OpenAPITools/openapi-generator/blob/8c6236b341c0e74c4cc18ea409f6fbf3d3dc114d/modules/openapi-generator/src/main/resources/php-slim4-server/model.mustache#L36
Could be the simplest solution change it to `public`?

Thank you for this beautiful project!

**Comment by ybelenko** [comment]
Hey, @TechPrivacyLab! Thanks for the interest to Slim4 server generator.

I've spent weeks on thinking how models for Slim4 server should look like. Unfortunately they will not look like classes we usually expect. At first, I thought about a clean class with the classic `__construct` and `factory` static method like `::createClassInstance()`. I don't like bunch of setters and getters, because there are `__set` and `__get` magic methods for the same purpose.

But... because of variety of referenced schemas and almost ultimate freedom on variables naming in OAS itself we can't implement models that way. Imagine model generated from enum string schema? Or from `type: array`. We also need to support `324weirdNamed Properties` which breaks PHP syntax.

My latest PR #5930 will extend models with my own [`OpenAPIServer\Mock\BaseModel`](https://github.com/ybelenko/openapi-data-mocker/blob/master/src/Mock/BaseModel.php) class. That's how I see it and I'm open to any criticism btw.

As you already noticed If you won't be satisfied with my implementation you can overwrite [models.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-slim4-server/model.mustache) template.

**Comment by TechPrivacyLab** [comment]
Hi @ybelenko, I like your approach regarding the `__construct` and the `factory` static methods rather than getters and setters.

I also like your good job with the `OpenAPIServer\Mock\BaseModel` class.

Here is my proposal:
1. Include the `OpenAPIServer\Mock\BaseModel` class in the generator
2. Update the current [`OpenAPIServer\Interfaces\ModelInterface`](https://github.com/OpenAPITools/openapi-generator/blob/8689625af33b60acc0e182d7e3c9153f29346aad/samples/server/petstore/php-slim4/lib/Interfaces/ModelInterface.php) with your newer [`OpenAPIServer\Mock\OpenApiModelInterface`](https://github.com/ybelenko/openapi-data-mocker-interfaces/blob/c5ce249a40501688fc561a436bc19672af935881/src/Mock/OpenApiModelInterface.php)
3. The models extends `OpenAPIServer\Mock\BaseModel`
4. The models be abstract classes, so anyone can extends them adding project-specific business logic
5. The models' properties must have `protected` access for a more generic extension

Pros:
1. Generic enough approach
2. Good starting toolbox

Users can extend models and they will have all the utility functions of the `OpenAPIServer\Mock\BaseModel` and they will can add project-specific business logic to the models. Or they will ignore them because the will not want them without any side effect.

Cons:
1. No solutions for more complex models (enum strings, array, weird properties, breaking syntax...) yet

What do you think?

In case you think your new classes are not stable enough a super simple first step could be adopt only 4. and 5. of the proposal to have in any case the 1. from the pros.

**Comment by ybelenko** [comment]
It seems that your 1 to 4 proposals already wait for review in #5930.

> 5. The models' properties must have protected access for a more generic extension

Can't quite follow you here... If I make properties `protected`, then I should disable `__get` and `__set` methods completely.

> 1. No solutions for more complex models (enum strings, array, weird properties, breaking syntax...) yet

You mean if I set properties protected? My current `BaseModel` handles scalar types and weird properties OK, because of `$dataContainer` and general `setData($data)`, `getData(): mixed` methods. It doesn't validate and doesn't convert data types yet, but I'm going to add it in next version.

> In case you think your new classes are not stable enough a super simple first step could be adopt only 4. and 5. of the proposal to have in any case the 1. from the pros.

I'm pretty satisfied with my `BaseModel` already, it completely covered with unit tests which is more than enough for `1.0.0` version. It doesn't support `allOf/anyOf/oneOf` keywords yet, that's my next goal.

**Comment by ybelenko** [comment]
I was writing setters and getters in my mocker repo and suddenly realized, that it shouldn't be part of mocking feature. Mock repo should contain model interface with only three public methods `getOpenApiSchema()`, `createFromData()` and `jsonSerialize()`.

So I'm moving current BaseModel implementation to Slim generator. Getters, setters, serialization, deseralization and model validation that's all should be developed right here, because I'm highly doubt that I can provide package with universal model implementation for Slim, Symfony and other PHP frameworks.

**Comment by ybelenko** [comment]
Closed in #5930
