### ISSUE TITLE
[REQ] Pre generation scripts

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#6741]
### Is your feature request related to a problem? Please describe.

Current `php-lumen` server generator contains 30 files where 2 files are dynamic and 28 files are static. We can wipe off 28 files because following command from Lumen documentation generates them for us:
```console
$  composer create-project --prefer-dist laravel/lumen lib
Creating a "laravel/lumen" project at "./lib"

                                                                                                                   
  [InvalidArgumentException]                                                                                       
  Project directory "/Users/ybelenko/Sites/openapi-generator/samples/server/petstore/php-lumen/lib" is not empty.  
```
But, this script refuses to generate project in non-empty directory.

## Describe the solution you'd like

Somehow I need to clean output directory(maybe with a warning of data loss) then run `composer create-project` and only after that run generation to overwrite dynamic files. It feels like I need PRE PROCESS script or something like that.

## Describe alternatives you've considered

Keep storing 28 static files like we did before. 

Or we can describe in readme that user needs to generate files, then move them in different folder, run `create project` script then move files back. In this scenario I guess that samples build will not pass CI because of missed files.

**Comment by ybelenko** [comment]
@wing328 and @jimschubert any suggestions?
Should I hardcode all static files into templates again?

**Comment by jimschubert** [comment]
I'm not familiar with PHP enough to say, but this seems like an issue with composer.

**Comment by ybelenko** [comment]
@jimschubert Composer or PHP it doesn't matter, can we run script before generation somehow?
There will be a lot of frameworks in future which suggest script installations I guess.

**Comment by jimschubert** [comment]
There's nothing stopping users from running a script before running openapi-generator. If we were to add that functionality to the generator, it has potential security implications. It also adds complication to the user because it's another abstraction (which we have to document and maintain). It would also extend openapi-generator from a single purpose generation tool to a build orchestration utility, and that's not really what the project is intended for.

Also, I don't see how that would change the above behavior. You're getting an error about a non-empty directory. If the problem is that PHP users have to run composer in a directory before running openapi-generator, I think the generator could have an option for static + dynamic output (without composer in the picture) and dynamic only (with documentation to first run composer).

I'd suggest maybe providing a build script with the php-lumen generator or better documenting how to integrate with those common tooling.

**Comment by ybelenko** [comment]
@jimschubert Thanks for a complete answer. I think you right, pre generation logic can make maintaining much more difficult.

So, I'll hardcode Lumen source files back into language templates for now. 
There may be a copyright issue. Let's look at generated sample:
https://github.com/OpenAPITools/openapi-generator/blob/6c1aecb1510665a6ecc9c6aab08ecef388050b39/samples/server/petstore/php-lumen/lib/app/User.php#L3-L20

which is exact copy of source file https://github.com/laravel/lumen/blob/master/app/User.php The only difference is `NOTE: This class is auto generated...` block comment. 

Is it appropriate to add this `NOTE: ...` comment or we should store framework source files as is?

**Comment by jimschubert** [comment]
@ybelenko I'd suggest adding the laravel license at the top of these files. That should be all that is necessary.

**Comment by ybelenko** [comment]
@jimschubert something like?
```php
/**
 * The Lumen framework is open-sourced software licensed under the [MIT license](https://opensource.org/licenses/MIT).
 */
```
I copied that line from https://github.com/laravel/lumen#license

**Comment by jimschubert** [comment]
Yeah I think that will work. They don't seem to have an official license header or even a LICENSE file to copy a longer license from.
