### ISSUE TITLE
[gradle-plugin] release a 5-beta version of the gradle plugin

### ISSUE THREAD

**Issue by huehnerlady** [OpenAPITools/openapi-generator#6858]
HI,

is it maybe possible to release a beta 5.0-beta version for the gradle plugin - aligned with the 5.0-beta release of the generator?

Many thanks

**Comment by wing328** [comment]
You mean this one: https://mvnrepository.com/artifact/org.openapitools/openapi-generator-gradle-plugin/5.0.0-beta ?

**Comment by wing328** [comment]
I think you're referring to this one: https://plugins.gradle.org/plugin/org.openapi.generator

cc @jimschubert

**Comment by jimschubert** [comment]
Thanks. This is a one-off issue whenever we do beta releases because of the travis.yaml regex:

![image](https://user-images.githubusercontent.com/109659/86541896-cbd56b00-bede-11ea-8516-b5429ec3cbad.png)

Rather than complicate the regex and potentially publish for tags we don't intend as releases, we'll just have to manually publish whenever we have a release candidate/beta.

Should be good to use now.

![image](https://user-images.githubusercontent.com/109659/86541892-ba8c5e80-bede-11ea-8269-0b83d4e1c607.png)

**Comment by huehnerlady** [comment]
@jimschubert @wing328 many thanks for your help. I was referring to the gradle plugin repository. so many thanks for manually releaseing 👍
