### ISSUE TITLE
Kotlin Server Ktor 0.9.3

### ISSUE THREAD

**Issue by scorsi** [OpenAPITools/openapi-generator#716]
Hi,

Actually, the generator support Kotlin Ktor Server 0.9.1, is there any future plan considering the upgrade to 0.9.3 ?

Thanks,

**Comment by wing328** [comment]
@scorsi I don't think anyone is working on that. May I know if you've time to contribute the enhancement? I can show you some good starting points.

**Comment by scorsi** [comment]
Yeah, please share me some good starting point like:
 - Where the repository/source is ?
 - If I understand, it's a kind of templating engine ? Is there some documentations ?

I have some projects in progress, I will see if I have the time for that.
Thanks,

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/build.gradle.mustache#L11 is a good starting point.

After updating the file, please also do a "mvn clean package" locally and run the following to update the Petstore samples so that CI can verify the change:
- Windows: `.\bin\windows\kotlin-server-petstore.bat`
- Linux: `./bin/kotlin-server-petstore.sh`

**Comment by scorsi** [comment]
Thank you, I will take a look at this.
