### ISSUE TITLE
[BUG] [DART-DIO] Generated client tries to parse jpeg body as JSON content

### ISSUE THREAD

**Issue by frameset** [OpenAPITools/openapi-generator#7225]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
https://raw.githubusercontent.com/gotson/komga/master/komga/docs/openapi.json
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
Yes
- [ ] What's the version of OpenAPI Generator used?
4.3.1
- [ ] Have you search for related issues/PRs?
Yes
- [ ] What's the actual output vs expected output?
Fails with a runtime error - Unexpected character.
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
A generated API client method should return an image in the form of a dart UInt8List, but the method throws a runtime error.:

```
Exception has occurred.
FormatException (FormatException: Unexpected character (at character 1)
```
Looking at the dio's requests, the status returned is 200, and the body is jpeg content. The generated code seems to fail during the serialization process I think. 
##### openapi-generator version
4.3.1 Not a regression as far as I am aware.

##### OpenAPI declaration file content or url
https://raw.githubusercontent.com/gotson/komga/master/komga/docs/openapi.json

##### Generation Details

java -jar .\openapi-generator-cli.jar generate -i 'https://raw.githubusercontent.com/gotson/komga/master/komga/docs/openapi.json' -g dart-dio -o .\komga_api_client\ 

##### Steps to reproduce

Instantiate an api object as above.

Call the method inside an async function like so:

`Response<Uint8List> thumbnailResponse = await api.getBookControllerApi().getBookThumbnail(book.id);`

**Comment by frameset** [comment]
https://openapi-generator.slack.com/archives/CLSB0U0R5/p1597622482059900 I discussed this with a member of the Dart technical committee on the slack, and it seems like the generator is not applying the `isFileResponse` part of the template.

**Comment by josh-burton** [comment]
@frameset it turns out dart-dio does support `isResponseFile` but it was just recently added so is only in the 5.0.0-beta version, not 4.3.1.

If you switch to the beta you should be all good. If you'd rather not use beta but still want that change then copy the api.mustache file from [here](https://github.com/OpenAPITools/openapi-generator/blob/v5.0.0-beta/modules/openapi-generator/src/main/resources/dart-dio/api.mustache) and use the [custom templates functionality of the generator](https://openapi-generator.tech/docs/templating/).

I think this issue can be closed.
