### ISSUE TITLE
[BUG][Python] Bug generating invalid Configuration class with missing access_token

### ISSUE THREAD

**Issue by zilvinasu** [OpenAPITools/openapi-generator#7468]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am generating  Python client for my OpenAPI and it is outputting invalid Python code, where it has a Configuration class, which is trying to use `self.access_token` which is not initialised to any default value.

##### openapi-generator version

v.4.2.0

##### Generation Details

```sh
docker run --rm \
		-v "${PWD}:/repo" openapitools/openapi-generator-cli generate \
		-i /repo/spec.yaml \
		-g python --package-name "my_api" \
		-o /repo/openapi/my_api
```

##### Related Issues
https://github.com/OpenAPITools/openapi-generator/issues/7929

##### Steps to reproduce

With generated client, just go to `configuration.py` you will see that `self.access_token` is being used, though it was not initialised anywhere.

##### Suggest a fix

Initialise access_token value to None by default

**Comment by codethief** [comment]
In code generated by openapi-generator-cli v4.3.1 I see the access token getting initialized: There's a line `self.access_token = None` in `Configuration.__init__()`. So maybe this issue has been fixed in the meantime? 

IMO the actual problem is this: The generated README.md currently says that the `access_token` could be passed to `Configuration()` but `Configuration.__init__()` actually doesn't have an `access_token` argument and (as noted above) `self.access_token` always gets set to `None`. This is quite confusing, considering that `Configuration.__init__()` accepts an `api_key` and a username/password as argument.

As a workaround I currently do:

```
config = Configuration()
config.access_token = "My access token"
```

**Comment by spacether** [comment]
This property can be set on the configuration instance. If you want to add access_token as an init parameter please file a PR.
