### ISSUE TITLE
[BUG] [typescript-angular] AllOf hierarchy produces api that doesn't compile

### ISSUE THREAD

**Issue by tschmidt01** [OpenAPITools/openapi-generator#8000]
**OpenAPI Spec**
```
openapi: 3.0.3

info:
  title: Demo
  version: 1.0.0
  description: Demo

paths:
  /some-path:
    post:
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtendedTransferObjectRequest'
      responses:
        201:
          description: some description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtendedTransferObjectResponse'

components:
  schemas:
    TransferObject:
      type: object
      properties:
        id:
          type: string
          format: uuid
    ExtendedTransferObject:
      type: object
      allOf:
        - $ref: '#/components/schemas/TransferObject'
        - type: object
      required:
        - some-field
      properties:
        some-field:
          type: string
    ExtendedTransferObjectRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/ExtendedTransferObject'
        - type: object
    ExtendedTransferObjectResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ExtendedTransferObject'
        - type: object
```

**Generated with**
```
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:latest generate -i /local/sample.yml -g typescript-angular -o /local/build
```

**Results in a `default.service.ts` file with a invalid import statement along with unused class `ExtendedTransferObject`:**
```
import { ExtendedTransferObject &amp; object } from '../model/models';
```

**Comment by mitsuru793** [comment]
I have the trouble, me too.
I use a template of typescript-fetch.
So, I can't use allOf.

**Comment by jon-v** [comment]
I'm also observing the same issue in typescript-fetch. As far as I can tell it seems general to all allOf constructions. It correctly generates an intersection type, but there seem to be two issues with the generated code:
1: The type intersection operator `&` is generated as `&amp;`, which obviously doesn't compile.
2: It attempts to use the intersection type definition directly in the import statement from models.

It might be worth pointing out that the same bug is not present in typescript-axios. Issue #1 described above is not occurring there (it correctly generates `&`), and #2 is a non-issue because the typescript-axios client puts models and API together in one big file.

**Comment by cl1ck** [comment]
> It might be worth pointing out that the same bug is not present in typescript-axios. Issue 1 described above is not occurring there (it correctly generates `&`), and 2 is a non-issue because the typescript-axios client puts models and API together in one big file.

I'm using typescript-axios and have both issues with the following configuration:
```json
{
  "withSeparateModelsAndApi": true,
  "apiPackage": "api",
  "modelPackage": "model",
  "useSingleRequestParameter": true,
  "generateAliasAsModel": true
}
```

**Comment by Webjin** [comment]
Any news on this issue?
