### ISSUE TITLE
[BUG] Broken generation of anyOf model in python client

### ISSUE THREAD

**Issue by generall** [OpenAPITools/openapi-generator#8044]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Python client model is generated with broken validation in case of anyOf specification.
Model entry point tends to validate any option with the fields from latest entrance, which make it impossible to create instance  other that the last option of anyOf.

##### openapi-generator version

latest + v5.0.0-beta3

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: Bug API
  version: 0.1.0

paths:
  /test/:
  
    post:
      summary: Update points in collection
      operationId: update_points
      requestBody:
        description: Points update operations
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PayloadInterface"
  
      responses:
        200:
          description: successful operation


components:
  schemas:
    PayloadInterface:
      anyOf:
      - properties:
          type:
            enum:
            - keyword
            type: string
          value:
            type: string
        required:
        - type
        - value
        type: object
      - properties:
          type:
            enum:
            - float
            type: string
          value:
            format: double
            type: number
        required:
        - type
        - value
        type: object

```

##### Generation Details

```
docker run --rm \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    -v "${PWD}:/local" openapitools/openapi-generator-cli:latest generate \
    -i /local/openapi.yaml \
    -g python \
    -o /local/test_client
```

##### Steps to reproduce

* Generate client with given specification and command.
* Try to create model `PayloadInterface` with `model = PayloadInterface(value="text", type="keyword")`
* Observe error: `Invalid value for 'type' (keyword), must be one of ['float']`

**Comment by wing328** [comment]
@generall thanks for reporting the issue.

cc @spacether

**Comment by pbortlov** [comment]
#8892 Is it connected?

**Comment by spacether** [comment]
This is happening because the definition of the properties in the anyOf schemas are being loaded into the composed schema class. This does a couple of bad things:
1. it treats those properties as being defined in the composed schema level including validations (this is not where those validations apply)
2. the type variable is defined once in each anyOf schema, so when it is set in the composed schema, they collide, and only one is used.

@wing328 this is another reason why I want CodegenModel/CodegenProperty/CodegenParameter/CodegenResponse.vars in a schema to not include any properties defined in that schema's composed schemas.
To fix this I first need to:
- fix additionalProperties in models https://github.com/OpenAPITools/openapi-generator/pull/8802
  - right now some models have additionalPropertiesType being defined as None when it should have a real value
- make the CodegenModel/CodegenProperty/CodegenParameter/CodegenResponse.vars only contain the properties defined in that schema https://github.com/OpenAPITools/openapi-generator/pull/8816

**Comment by spacether** [comment]
This is happening because the anyOf definitions are Inline schemas. If you separate them into their own components then it should work. Another solution here is to switch to the python-experimental generator which supports Inline schema use cases like this one.

**Comment by spacether** [comment]
This works in `python-experimental` please use it
