### ISSUE TITLE
[JAXRS-spec] Make path for openapi.yaml configurable

### ISSUE THREAD

**Issue by michbeck100** [OpenAPITools/openapi-generator#809]
Currently the path of the generated openapi.yaml is always "src/main/openapi" (see [here](https://github.com/OpenAPITools/openapi-generator/blob/7acba8a4d86b3cdadc5707345817513dad11c36f/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java#L130)). This should be configurable, because the microprofile openapi spec, for example, needs the openapi.yaml at the [META-INF](https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#421-location-and-formats) folder.

**Comment by jmini** [comment]
I totally agree with this request because this allow to support MicroProfile without annotation (see discussion in #795).

I have also seen your PR https://github.com/OpenAPITools/openapi-generator/pull/813 that is also a step to support "MicroProfile without annotation". I will review it ASAP.

---

In my opinion we should have a new generator for that:
`java-microprofile-without-annotation` that configures the options of `JAXRS-spec` and also create the correct README and pom.xml to be able to bootstrap a MicroProfile in a user-friendly way.

It will be a reuse of almost everything of "JAXRS-spec".

What do you think?
