### ISSUE TITLE
[python-flask] Can't specify more than one value in -Dmodels

### ISSUE THREAD

**Issue by csimmons0** [OpenAPITools/openapi-generator#811]
##### Description

If I use the -Dmodels argument to specify which models to generate and I specify more than one model, only the first is generated. Wrapping the list of model names in quotes does not fix the problem. I experience the same problem with -DsupportingFiles.

I took a look at the code in modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, but I couldn't see an issue with it.

##### openapi-generator version

3.2.0

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml

##### Command line used for generation

```
$ openapi-generator generate -i ./petstore.yaml -g python-flask -o ./server -Dmodels=Pet,Tag
```

##### Steps to reproduce

```
~/openapi_issue
$ openapi-generator generate -i ./petstore.yaml -g python-flask -o ./server -Dmodels=Pet,Tag
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/csimmons/openapi_issue/./server/openapi_server/models/pet.py
~/openapi_issue
$ rm -rf ./server/
~/openapi_issue
$ openapi-generator generate -i ./petstore.yaml -g python-flask -o ./server -Dmodels=Tag,Pet
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/csimmons/openapi_issue/./server/openapi_server/models/tag.py
```

**Comment by wing328** [comment]
@csimmons0 can you try the following by putting the `-Dmodels` at the beginning of the command line argument?
```
$ openapi-generator -Dmodels=Tag,Pet generate -i ./petstore.yaml -g python-flask -o ./server
```

**Comment by jmini** [comment]
I am at the root of this repo (cloned locally)
I have run `mvn verify` once

Then I enter:

```
java -Dmodels=Order,Pet -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i modules/openapi-generator/src/test/resources/2_0/petstore.yaml -g python-flask -o ./out
```

And I get:
```
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - No .openapi-generator-ignore file found.
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jbr/Git/openapi-generator/./out/openapi_server/models/order.py
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jbr/Git/openapi-generator/./out/openapi_server/models/pet.py
```

This is the expected result.

I have the feeling you are using Homebrew. Is that correct? If not, what is the `openapi-generator` command you enter?

**Comment by jmini** [comment]
Ok I took an other look at the problem.

In our code we do a `System.getProperty("models")`:
https://github.com/OpenAPITools/openapi-generator/blob/6a47d49ee807293d4ac37e9d3f96e4a52ef4322c/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java#L134

But if you put `-Dmodels=Order,Pet` after the `-jar` line, the app is responsible to parse it.

So this is what we are doing in the `Generate` command:
https://github.com/OpenAPITools/openapi-generator/blob/6a47d49ee807293d4ac37e9d3f96e4a52ef4322c/modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java#L78-L83

But then line 332:
https://github.com/OpenAPITools/openapi-generator/blob/6a47d49ee807293d4ac37e9d3f96e4a52ef4322c/modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java#L332

tries to pass the content of `systemProperties` to the configurator.
At this point `systemProperties` is a `List<String>` containing a single value `"models=Order,Pet"` (correct).
The result in `configurator` is wrong:
`configurator.getSystemProperties()` is returning a Map with 2 entries:

1. key `"models"` value `"Order"`
2. key `"Pet"`, value `""` (empty string)

This is wrong because later in `toClientOptInput()`, `CodegenConfigurator.setSystemProperties()` is called here:
https://github.com/OpenAPITools/openapi-generator/blob/6a47d49ee807293d4ac37e9d3f96e4a52ef4322c/modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java#L491-L499

And the implementation distributes the content of the map as system property:
https://github.com/OpenAPITools/openapi-generator/blob/6a47d49ee807293d4ac37e9d3f96e4a52ef4322c/modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java#L628-L632

**Comment by keeed** [comment]
Since this issue is still open and in case anyone is using an Ant based task and is using java to build the code-gen, here's how to pass it.

Example:
``` xml
    <java .... >
        ...
        <jvmarg value="-Dmodels=Order,Pet"/>
        <jvmarg value="-DsupportingFiles=JSON.java,ApiException.java,ApiResponse.java"/>
        <arg value="generate" />
         ...
    </java>
```

**Comment by wing328** [comment]
@wing328 thanks for sharing the tips.
