### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by tkalmar** [OpenAPITools/openapi-generator#8320]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

After generating a native client with the maven plugin, our project no longer compiles with version 5.0.0
The culprit are the
```
import javax.ws.rs.core.GenericType;
import javax.ws.rs.ext.ContextResolver;
```
statements in the new JSON.java. The cause of this is AFAICT: https://github.com/OpenAPITools/openapi-generator/pull/7263
which introduces the dependencies to the jersey classes in the templates.

AbstractOpenApiSchema also has an import:
```
import javax.ws.rs.core.GenericType;
```
The generated client is no longer native but depends on jakarta.ws.rs, the new Dependency is nowhere documented

##### openapi-generator version

5.0.0 java (library:native) - works in 4.X so this is a regression

##### OpenAPI declaration file content or url
Any file should do, here is a minimal example

```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "api"
  },
  "host": "example.org",
  "basePath": "/api",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/ping": {
      "get": {
        "description": "ping",
        "operationId": "ping",
        "responses": {
          "200": {
            "description": "ping successful"
          }
        }
      }
    }
  }
}
```

##### Generation Details
java - library: native

##### Steps to reproduce

generate the api and try to compile it. (In our case a project which does not depend on jakarta.ws.rs)

##### Suggest a fix
Remove the jakarta.ws.rsdependencies from the templates if no anyOf, allOf is used
JSON.java and AbstractOpenApiSchema.java are not needed in this case. The unuses import in all model classes to JSON.java can also be left out

**Comment by tkalmar** [comment]
Also happens when switching the library to `resttemplate`

**Comment by carlkuesters** [comment]
Any news on this? I also just used the "native" template and saw that there are these javax.ws.rs dependencies. :(

**Comment by wtrocki** [comment]
Same problem happens with resteasy

**Comment by fabiohecht** [comment]
same issue with <library>okhttp-gson</library>

**Comment by martin-mfg** [comment]
It seems this issue is no longer valid. I tested with OpenAPI Generator 7.0.1, and no javax* or jakarta* imports were generated.

In addition, this also doesn't seem to be an actual issue in OpenAPI Generator 5.0.0. There, indeed the mentioned javax* imports are generated. But the generated pom.xml (.../target/generated-sources/openapi/pom.xml) contains the corresponding dependency on `javax.ws.rs-api`. Running `mvn clean verify` inside the generated `.../target/generated-sources/openapi/` directory succeeds without errors.

I assume people in this thread used a different pom.xml instead of the generated one. In cases where users use their own pom.xml, the easiest "fix" is to copy the dependencies from the generated pom.xml to your custom pom.xml.
