### ISSUE TITLE
[BUG] Is it expected that generated python client code now depends on nulltype

### ISSUE THREAD

**Issue by meadsteve** [OpenAPITools/openapi-generator#8371]
##### Description
We've previously been running v5.0.0-beta2. Switching to the full release v5.0.0 results in the error `ModuleNotFoundError: No module named 'nulltype'`.

The fix was to add the nulltype package to my project's requirements but I'm not sure if this is expected and it doesn't seem ideal. Is this package really required or was it an accidentally inclusion?

##### openapi-generator version
v5.0.0

**Comment by spacether** [comment]
This is an accident
nulltype is still in the mustache template here: https://github.com/OpenAPITools/openapi-generator/blame/master/modules/openapi-generator/src/main/resources/python/model_templates/method_init_composed.mustache#L30

In my original composition pr here: https://github.com/OpenAPITools/openapi-generator/pull/5341/files#r379938730
nulltype.Null was used as the default value of required oneOf properties in a composed schema's init signature.
Since then, setting that nulltype.Null default value has been removed so:
- addNullDefaultToOneOfAnyOfReqProps should be removed from modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java
- the if nulltype.Null check should be removed from https://github.com/OpenAPITools/openapi-generator/blame/master/modules/openapi-generator/src/main/resources/python/model_templates/method_init_composed.mustache#L30

**Comment by deeplook** [comment]
I wonder what the justification for using the `nulltype` package really is? Looking at the code, it is more imported than used. And where it is used it's always with testing for `nulltype.Null`. Is that really worth doing and adding one more dependency which is not even available on conda-forge?

**Comment by spacether** [comment]
Hey there. The comment above describes why null type was added. As described in that comment it can now be removed.

**Comment by spacether** [comment]
This has been resolved by the above PR. nulltype is no longer included in the python generator.
