### ISSUE TITLE
[BUG][swift5] Closure isn't called anymore in latest snapshot with default configuration

### ISSUE THREAD

**Issue by fl034** [OpenAPITools/openapi-generator#8511]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

This project showcases a weird error where callback closure is not called.

- This happens with the default library selected (URLSession). With Alamofire, everything is fine.
- In the 5.0.0 stable version, the error is not happening
- Snapshot Commit: 90ed1290fafe08306283f9acb74650e5b8d19302 from 2020-01-22
- Tested with Xcode 12.3 (12C33) on macOS Catalina 10.15.7 (19H15)
- Try switching the generator from snapshot to stable pod in `Podfile` to see the change.

##### openapi-generator version

5.0.1-snapshot (commit 90ed1290fafe08306283f9acb74650e5b8d19302)

##### OpenAPI declaration file content or url

See test-project: https://github.com/fl034/Test-OAS

##### Generation Details

- Swift5 with defaults

##### Steps to reproduce

Run sample project

##### Related issues/PRs

Nothing found

##### Suggest a fix

- The issue seems to be in `URLSessionImplementations.swift` in line 137. `self` seems to be deallocated immediately, because it’s weak. 
- When I remove `[weak self]` it works again. But this isn’t the root of the problem, since the stable version also has `[weak self]`

**Comment by 4brunu** [comment]
@fl034 you are rigth.
The problem was introduced in https://github.com/OpenAPITools/openapi-generator/commit/dd9a19ab8ffb01acabee694b3f142e51ef6813c7, when in URLSessionImplementations.swift line when `self.observation?.invalidate()`was removed from the `cleanupRequest` closure.
This closure was passed inside the `URLSession` response callback which was retaining self (URLSessionImplementations) in memory.
Now since there is no reference to self (URLSessionImplementations) because the `URLSession` response callback has `[weak self]`, the URLSessionImplementations is instantly removed from memory.

I think the solution is to remove `[weak self]`, what do you think?

**Comment by fl034** [comment]
Hey Bruno, thanks for this thorough error search.
Removing the `[weak self]` seems like the obvious solution. But what is with the inner closure?

https://github.com/OpenAPITools/openapi-generator/blob/646bcc64add4cfce7dfbe78195dd727bd11cb5d0/modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache#L135-L146

I'd suggest removing the `[weak self]` here too. What do you say?

**Comment by 4brunu** [comment]
I agree!
Do you want to create a PR with those changes, or do you me to do it?

**Comment by fl034** [comment]
I'm happy to do the PR :-)

**Comment by 4brunu** [comment]
Nice, thanks for your help 👍😊
