### ISSUE TITLE
Split Repository

### ISSUE THREAD

**Issue by mickroll** [OpenAPITools/openapi-generator#8953]
First of all, thank you for maintaining OpenAPI! We use it to quite an extent for our spec-first APIs.

But i have to say, it seems this project/repository is growing beyond being managable. Each change in the core has to be accompanied by a change to literally a hundred generators, tests, and so on within the same PR.
No one could possibly understand each and every specialty of each generator.
Just have a look at https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources and check if you understand all of them. If so, congratulations: that would be quite an accomplishment by itself.
Also, there are 85 branches (as of 11.03.2021) in this repository. By looking at their names, most of them relate to generators of specific languages.
Additionally, there are around 2000 open bugs. Which of those are not related to a generator, but to the core? I tried to find out, but in the end I simply stopped caring about. Not a good thing.
In these circumstances, don't expect your contributors to know what's going on. Taking part and trying to fix a Bug myself is really hard and i stopped to try so, too. If i am not the only one that reacts like this, it might explain the amount of open issues.

My recommendation: split this large repository
- core with model for API-contents, with a defined release-cycle
- maven plugin
- gradle plugin
- A repository for each language, or maybe even a repository for each generator. These could depend on specific versions of the core and migrate to newer releases step-by-step, with their own language specific maintainers and specialists.

This way, the community could implement their own language-generators, depending solely on the core and its API

**Comment by Blackclaws** [comment]
Let me respond to some of your points from my point of view having contributed a bit to the project in the last weeks:

The fact that it is a monolithic blob which a lot of features crammed into a single release might be daunting when trying to get started on improving/adding to the project.

For me the entry point into the system has always been a concrete generator that I was working on. Seeing that either the output wasn't what I wanted. That then brought me further and further into the core until I found the point where I wanted to make changes. I'm sort of treating this as "test driven development" with the output of the generator being the test result.

It has worked pretty well for me, but I can understand why it might not work so well for other people especially if you are coming from a spec end of things.

Regarding the amount of open bugs and pull requests, I agree that this needs some cleanup and I intend to actually go through the csharp related issues and try to get those cleaned up/fixed as well as possible.

I do actually think that understanding every specialty of every generator is not really needed if you are making changes to only some of them. Having the before/after check of generating the samples after making a change is also a nice check whether you might have broken something specific. 

I have worked on the csharp generator without ever worrying about any of the other generators. In the cases where I did have to make changes to the DefaultCodegen which affected others I also did not have to worry about a specific generator as I was changing base behaviour.

Regarding a split of this repository there are a couple of drawbacks:

- Splitting the core and the generator means that bugs fixed in the core don't get propagated to the generators until their next release (which depending on the generator might be never, if its not maintained)
- Splitting also means changes to the core and their impact to the generators becomes a lot harder to track
- If you require coordinated changes to both the core and a generator that becomes a merge train instead of a single pull request also complicating matters

I think what would amount to an equal improvement without the split is an improvement in the documentation for new developers on how to get started working with this repository and maybe some restructuring on certain parts.

I'd love to get the opinion of @OpenAPITools/generator-core-team

**Comment by agilob** [comment]
>A repository for each language, or maybe even a repository for each generator. These could depend on specific versions of the core and migrate to newer releases step-by-step, with their own language specific maintainers and specialists.

This sounds bad to me, adding new generator, fixing bugs and updating the main/core with all generators would be a bi-directional dependency hell. I agree about autogenerated documentation, it shouldn't live here.

> Additionally, there are around 2000 open bugs. Which of those are not related to a generator, but to the core? I tried to find out, but in the end I simply stopped caring about. Not a good thing.

Most of them are support requests or help queries, people refuse to close them even after finding solution to "how to use it with gradle". So many of them belong to stackoverflow I can't even... I responded to 3 in the last week, none of them was closed. I feel issue moderation in this repo is slowly managed, help request shouldn't land here, legitimate issues are quickly buried and never talked about. Same for PRs, so many of them are unrelated, super-low effort, authors didn't even bother to read PR template and update samples after adding their fix.

A few of tech-comettee lists are out of date, many generators like typescript-angular were donated here and then abandoned, despite they are buggy and cause problems for many users except author or the generator.

I personally think this repo needs stronger moderation than spitting into more repos. Closing unrelated issues, out of date PRs, removal of deprecated generators unless maintainer is found (6 months eviction notice). This repo is a really good example of cathedral-bazaar model, a few main generators and many accompanying smaller generators working together on a one big market, such market needs a police and cleaning service ;)

**Comment by wing328** [comment]
Thanks for the reply from @Blackclaws and @agilob in which I mostly agree.

We've considered splitting repo before but gave up the idea partially based on the reasons provided above. We also notice some other code generators out there use such approach but end up being abandoned.

@mickroll if you need to change something in the default codegen, I would recommend open an "issue" to start the discussion first with the details on your use case as likely there are ways to meet your requirement by changing just the generator but not the default codegen (and we use the issue tracker for non-issue discussion as well)

**Comment by mickroll** [comment]
Thank you for your input. I see you have discussed splitting the repo before, so i'll close this issue.
