### ISSUE TITLE
[BUG] [Dart] Setting nullable:false is not respected

### ISSUE THREAD

**Issue by harsimranmaan** [OpenAPITools/openapi-generator#9195]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

5.1.1

##### OpenAPI declaration file content or url
https://github.com/bigpanther/trober/blob/3c80a730cf9fa8e4bf9813ba4f82ea2dffaf61ac/sdk/trober.yaml 

##### Generation Details
The Tenant id field is set as `nullable: false` but is generated as a nullable field in dart-dio-next generator. Note that fields marked as required are generated as non nullable. 

##### Steps to reproduce

```bash
java -jar openapi-generator-cli.jar generate -i https://github.com/bigpanther/trober/blob/3c80a730cf9fa8e4bf9813ba4f82ea2dffaf61ac/sdk/trober.yaml  -g dart-dio-next -o trober_sdk
```

##### Suggest a fix

I am not very well versed with the openapi spec on nullable and required fields. As a workaround, I can mark the fields as required but would prefer to avoid it if I can. Next, I'll try setting a default value to see how it affects the behaviour.

cc: @kuhnroyal

**Comment by kuhnroyal** [comment]
`nullable: false` basically says `tenant_id: null` is not allowed in the wire format. Instead the field should be omitted.
Required fields may be nullable, these are 2 different things.

So if `tenant_id` is required, then you need to make it `required`. If you just don't want to receive `tenant_id: null` on the server, then you need to make it `nullable: false`. If you want both, you need to set both.

`required` and `nullable` define the wire format, and do not necessarily translate to Dart in the understanding of NNBD.

We are using this in the template:
```mustache
{{{datatypeWithEnum}}}{{#isNullable}}?{{/isNullable}}{{^isNullable}}{{^required}}?{{/required}}{{/isNullable}} get {{name}};
```
And `required` and `nullable` are also evaluate when serializing:
```mustache
        {{#required}}
        {{!
            A required property need to always be part of the serialized output.
            When it is nullable, null is serialized, otherwise it is an error if it is null.
        }}
        result
            ..add(r'{{baseName}}')
            ..add({{#isNullable}}object.{{{name}}} == null ? null : {{/isNullable}}serializers.serialize(object.{{{name}}},
                specifiedType: {{{vendorExtensions.x-built-value-serializer-type}}}));
        {{/required}}
        {{^required}}
        if (object.{{{name}}} != null) {
            {{! Non-required properties are only serialized if not null. }}
            result
                ..add(r'{{baseName}}')
                ..add(serializers.serialize(object.{{{name}}},
                    specifiedType: {{{vendorExtensions.x-built-value-serializer-type}}}));
        }
        {{/required}}
```

And there is a little more to this. A `required` field can be `nullable` in OAS3 but in order to figure this out we would need something in Dart that can tell us if a value is absent. Absent is not `null` in OAS3 but there is no way in Dart to define this with on-board means.

I hope this helps in understanding the current generation. I think in your case this is correctly generated. If you have any more questions, don't hesitate to ask.
