### ISSUE TITLE
[swift5] Upgrade to Alamofire 5

### ISSUE THREAD

**Issue by jfrtree** [OpenAPITools/openapi-generator#9218]
### Is your feature request related to a problem? Please describe.

No
## Describe the solution you'd like

Upgrade swift5 Alamofire dependency to AF5
## Describe alternatives you've considered

Considered writing an Alamofire5 RequestBuilder into my project.  But if support/interest in Alamofire is on the decline, it may make sense just to move to URLSession

**Comment by wing328** [comment]
@jfrtree thanks for offering help on this. We definitely welcome PRs to update Alamofire to the latest stable version.

**Comment by 4brunu** [comment]
@jfrtree just curious, why do you want to use alamofire instead of URLSession?

Honestly alamofire is there just because of legacy reasons, it was there before so I kept it.

But since URLSession was introduced in the Swift generator, I can't see any use case where it would be better to use alamofire instead of URLSession.

I was even thinking in proposing to remove alamofire from the Swift generator.

**Comment by muellnes** [comment]
@4brunu I definitely would also prefer to have a plain URLSession implementation, so that in the best case you do not introduce any dependencies with the generated API code.
Stil I would favor for various reasons this to be an option e.g. Alamofire/UrlSession

Also there are also still some advantages of using Alamofire, like:
-  cURL Command Output
-  Dynamically Adapt and Retry Requests
-  TLS Certificate and Public Key Pinning
-  Network Reachability

**Comment by 4brunu** [comment]
@muellnes thanks for your feedback.

Based on your feedback, I think it's valuable to keep the Alamofire and upgrade it.

**Comment by 4brunu** [comment]
I created https://github.com/OpenAPITools/openapi-generator/pull/10292 that should fix this.
@muellnes @jfrtree could you please test it in your projects to see if it's working?
Thanks

**Comment by muellnes** [comment]
@4brunu Thank you for the changes. For me everything did work as expected with the latest changes.
