### ISSUE TITLE
[BUG][C#][csharp-netcore] maxLength + enum = generated code doesn't build

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [OpenAPITools/openapi-generator#9586]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When an object property features `maxLength` (and possibly other similar attributes?) alongside an `enum`, the generated code does not compile.
Now, I know this is kind of weird to have both enum values and maxLength defined but the spec doesn't prevent those for the reasons stated [here](https://github.com/OAI/OpenAPI-Specification/issues/2153#issuecomment-590190022).
Which means that the validators won't catch these, the generator will run fine, only at the final step of building a package the error would show up.

##### openapi-generator version

master @ e09409fbce

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: C# enum length repro
  version: v1
paths:
  '/hello':
    get:
      responses:
        '200':
          description: returns a greeting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'

components:
  schemas:
    Greeting:
      type: object
      properties:
        reply:
          type: string
          maxLength: 20
          enum:
            - hi
            - howdy
```

##### Generation Details

See steps below.

##### Steps to reproduce

```
openapi-generator generate -i openapi.yaml -g csharp-netcore --library httpclient -o out/csharp_enum
cd out/csharp_enum 
dotnet build --configuration Release
```

produces:

```
(...)
out/csharp_enum/src/Org.OpenAPITools/Model/Greeting.cs(141,49): error CS1061: 'Greeting.ReplyEnum?' does not contain a definition for 'Length' and no accessible extension method 'Length' accepting a first argument of type 'Greeting.ReplyEnum?' could be found (are you missing a using directive or an assembly reference?)
(...)

Build FAILED.
```

##### Related issues/PRs

None that I could find.

##### Suggest a fix

No idea... 🙇 

@mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti @wing328 @prajon84

**Comment by Blackclaws** [comment]
Right, so I'm not sure if this a bug per se or a quirk of the way json schema linting works. I mean we could catch this as a special nonsense case somewhere in the default generator if that would help in this case? It won't work in any case as for example its entirely unclear to me what happens if you specify an enumvalue that is longer than the maxlength.

**Comment by jfeltesse-mdsol** [comment]
I'm not familiar with C# so I can't go deep into the implementation details but conceptually, the type of the property is `string` so it should accept the attributes related to string types to be set, however meaningless they may be. The enum case may be handled by a list of acceptable strings and a check going like (pseudo code) `acceptableValues.include?(passedValue)` instead of making an enum type that's too restrictive for the OpenAPI purpose.
Just my 2円.

> its entirely unclear to me what happens if you specify an enum value that is longer than the maxlength.

The schema instance will never be deemed valid. That's how JSON Schema works, you can very well shoot yourself in the foot with conflicting rules, _c'est la vie_.

**Comment by Blackclaws** [comment]
Well the enum type is restrictive and there will be a deserialization error if the returned value does not conform to the list of values.

So that type of check is already in place by convention as you cannot deserialize an enum value that was not defined.

I think that not creating an enum type when enum is specifically requested is also contrary to what the spec specifies even if the underlying over the wire type is string its still declaring that only a set number of strings can ever be passed. Max Length is kind of implicitly set to the longest string in that enum list that way.

I am against changing the Enum implementation in c# to use plain strings instead as that wouldn't make any sense really in this context.

**Comment by jfeltesse-mdsol** [comment]
I hear you but the point is, however non sensical or redundant an attribute may be, as long as the user feeds in a valid OpenAPI file the generator shouldn't generate code that won't compile.

In our case here, if the enum type is the best solution (again, not so familiar with C#), then some clean up of the undesirable attributes (minLength, maxLength, ...) that we know will trip the generator might be an option?

**Comment by Blackclaws** [comment]
Yeah I think cleaning up the validation of those parameters is for the best. I'm not sure that there is another way to validate this. In general I think any OpenAPI spec where the enum values and the max/minLength don't match should be invalid regardless of whether it fits the schema or not as it is essentially contradictory. The fix is simple and I'll open a quick pull request.
