### ISSUE TITLE
Is it possible to run openapi-generator-cli from source without compiling the jar?

### ISSUE THREAD

**Issue by ndbroadbent** [OpenAPITools/openapi-generator#965]
I've found that it's easier if I can just fork the `openapi-generator` repo and modify the source code directly. This is because I need to update files like `RubyClientCodegen.java` to add some new mustache templates.

I've been compiling with `mvn install -DskipTests=true`, but it would be great if I could skip this step and just run the `.java` file directly, to save some time.

I'm not too familiar with Java, but would this be possible? Would anyone be able to provide a command-line example? Thanks!

**Comment by ndbroadbent** [comment]
This was answered here: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#creating-a-new-template

**Comment by jmini** [comment]
Using:
```
mvn package -DskipTests -Dmaven.javadoc.skip=true
```
speeds up the maven build a little bit.

But creating the official cli project still takes time, because all sources are transformed into a jar.

----

Personally I am using Eclipse IDE. With its incremental compiler, I do not see compile time when I start the generators.

---

An other approach could be to use a generator in a separated project (can be a maven project, that you build from the command line). Then you just recompile this one instead of the complete project and the complete cli. Someone just started a discussion about this in #964.

Then you can run the official cli, the official cli, or the official gradle plugin with your additional generator. When a change is requested in the generator, you need only to recompile only this generator.

---

Do not hesitate if you need some help with one of the approach.

**Comment by ndbroadbent** [comment]
@jmini Thanks very much! I also just found the documentation about creating a custom generator. That looks like the right approach for me, and then I also don't need to modify the source code of `openapi-generator`.
